"""
main.py  —  31OPT Optics Manim Video Series
============================================
Usage:
    python main.py --list       # print all render commands (python -m manim -qh ...)
    python main.py --filelist   # print ffmpeg concat file list
    python main.py --scenes     # print all scene names grouped by file
"""
import argparse
from pathlib import Path

# ── Complete scene list in playback order ─────────────────────────────────────
# Format: (python_file, SceneClass)
RENDER_ORDER = [

    # week1_waves.py
    ("week1_waves.py", "Week1TitleCard_p1"),
    ("week1_waves.py", "Week1TitleCard_p2"),
    ("week1_waves.py", "Week1TitleCard_p3"),
    ("week1_waves.py", "Week1TitleCard_p4"),
    ("week1_waves.py", "WaveIntroduction_p1"),
    ("week1_waves.py", "WaveIntroduction_p2"),
    ("week1_waves.py", "WaveIntroduction_p3"),
    ("week1_waves.py", "WaveIntroduction_p4"),
    ("week1_waves.py", "WaveIntroduction_p5"),
    ("week1_waves.py", "WaveIntroduction_p6"),
    ("week1_waves.py", "WaveEquation1D_p1"),
    ("week1_waves.py", "WaveEquation1D_p2"),
    ("week1_waves.py", "WaveEquation1D_p3"),
    ("week1_waves.py", "WaveEquation1D_p4"),
    ("week1_waves.py", "WaveEquation1D_p5"),
    ("week1_waves.py", "WaveEquation1D_p6"),
    ("week1_waves.py", "WaveEquation1D_p7"),
    ("week1_waves.py", "WaveEquation1D_p8"),
    ("week1_waves.py", "WaveEquationProof_p1"),
    ("week1_waves.py", "WaveEquationProof_p2"),
    ("week1_waves.py", "WaveEquationProof_p3"),
    ("week1_waves.py", "WaveEquationProof_p4"),
    ("week1_waves.py", "WaveEquationProof_p5"),
    ("week1_waves.py", "HarmonicWave_p1"),
    ("week1_waves.py", "HarmonicWave_p2"),
    ("week1_waves.py", "HarmonicWave_p3"),
    ("week1_waves.py", "HarmonicWave_p4"),
    ("week1_waves.py", "HarmonicWave_p5"),
    ("week1_waves.py", "HarmonicWave_p6"),
    ("week1_waves.py", "HarmonicWave_p7"),
    ("week1_waves.py", "HarmonicWave_p8"),
    ("week1_waves.py", "HarmonicWave_p9"),
    ("week1_waves.py", "HarmonicWave_p10"),
    ("week1_waves.py", "HarmonicWave_p11"),
    ("week1_waves.py", "HarmonicWave_p12"),
    ("week1_waves.py", "HarmonicWave_p13"),
    ("week1_waves.py", "HarmonicWave_p14"),
    ("week1_waves.py", "HarmonicWave_p15"),
    ("week1_waves.py", "HarmonicWave_p16"),
    ("week1_waves.py", "HarmonicWave_p17"),
    ("week1_waves.py", "HarmonicWaveExample_p1"),
    ("week1_waves.py", "HarmonicWaveExample_p2"),
    ("week1_waves.py", "HarmonicWaveExample_p3"),
    ("week1_waves.py", "HarmonicWaveExample_p4"),
    ("week1_waves.py", "HarmonicWaveExample_p5"),
    ("week1_waves.py", "HarmonicWaveExample_p6"),
    ("week1_waves.py", "HarmonicWaveExample_p7"),
    ("week1_waves.py", "HarmonicWaveExample_p8"),
    ("week1_waves.py", "HarmonicWaveExample_p9"),
    ("week1_waves.py", "HarmonicWaveExample_p10"),
    ("week1_waves.py", "SuperpositionPrinciple_p1"),
    ("week1_waves.py", "SuperpositionPrinciple_p2"),
    ("week1_waves.py", "SuperpositionPrinciple_p3"),
    ("week1_waves.py", "SuperpositionPrinciple_p4"),
    ("week1_waves.py", "SuperpositionPrinciple_p5"),
    ("week1_waves.py", "SuperpositionPrinciple_p6"),
    ("week1_waves.py", "PhaseGroupVelocity_p1"),
    ("week1_waves.py", "PhaseGroupVelocity_p2"),
    ("week1_waves.py", "PhaseGroupVelocity_p3"),
    ("week1_waves.py", "PhaseGroupVelocity_p4"),
    ("week1_waves.py", "PhaseGroupVelocity_p5"),
    ("week1_waves.py", "PhaseGroupVelocity_p6"),
    ("week1_waves.py", "PhaseGroupVelocity_p7"),
    ("week1_waves.py", "ComplexRepresentation_p1"),
    ("week1_waves.py", "ComplexRepresentation_p2"),
    ("week1_waves.py", "ComplexRepresentation_p3"),
    ("week1_waves.py", "ComplexRepresentation_p4"),
    ("week1_waves.py", "ComplexRepresentation_p5"),
    ("week1_waves.py", "ComplexRepresentation_p6"),
    ("week1_waves.py", "ComplexRepresentation_p7"),
    ("week1_waves.py", "ComplexRepresentation_p8"),
    ("week1_waves.py", "ComplexRepresentation_p9"),
    ("week1_waves.py", "ThreeDWaves_p1"),
    ("week1_waves.py", "ThreeDWaves_p2"),
    ("week1_waves.py", "ThreeDWaves_p3"),
    ("week1_waves.py", "ThreeDWaves_p4"),
    ("week1_waves.py", "Week1WavesSummary_p1"),
    ("week1_waves.py", "Week1WavesSummary_p2"),
    ("week1_waves.py", "Week1WavesSummary_p3"),
    ("week1_waves.py", "Week1WavesSummary_p4"),
    ("week1_waves.py", "Week1WavesSummary_p5"),
    ("week1_waves.py", "Week1WavesSummary_p6"),
    ("week1_waves.py", "Week1WavesSummary_p7"),

    # week1_maxwell.py
    ("week1_maxwell.py", "MaxwellIntro_p1"),
    ("week1_maxwell.py", "MaxwellIntro_p2"),
    ("week1_maxwell.py", "MaxwellIntro_p3"),
    ("week1_maxwell.py", "MaxwellIntro_p4"),
    ("week1_maxwell.py", "VectorCalculusNotation_p1"),
    ("week1_maxwell.py", "VectorCalculusNotation_p2"),
    ("week1_maxwell.py", "VectorCalculusNotation_p3"),
    ("week1_maxwell.py", "VectorCalculusNotation_p4"),
    ("week1_maxwell.py", "VectorCalculusNotation_p5"),
    ("week1_maxwell.py", "MaxwellEquations_p1"),
    ("week1_maxwell.py", "MaxwellEquations_p2"),
    ("week1_maxwell.py", "MaxwellEquations_p3"),
    ("week1_maxwell.py", "MaxwellEquations_p4"),
    ("week1_maxwell.py", "MaxwellEquations_p5"),
    ("week1_maxwell.py", "MaxwellEquations_p6"),
    ("week1_maxwell.py", "MaxwellEquations_p7"),
    ("week1_maxwell.py", "MaxwellVacuum_p1"),
    ("week1_maxwell.py", "MaxwellVacuum_p2"),
    ("week1_maxwell.py", "MaxwellVacuum_p3"),
    ("week1_maxwell.py", "MaxwellVacuum_p4"),
    ("week1_maxwell.py", "EMWaveDerivation_p1"),
    ("week1_maxwell.py", "EMWaveDerivation_p2"),
    ("week1_maxwell.py", "EMWaveDerivation_p3"),
    ("week1_maxwell.py", "EMWaveDerivation_p4"),
    ("week1_maxwell.py", "EMWaveDerivation_p5"),
    ("week1_maxwell.py", "EMWaveProperties_p1"),
    ("week1_maxwell.py", "EMWaveProperties_p2"),
    ("week1_maxwell.py", "EMWaveProperties_p3"),
    ("week1_maxwell.py", "EMWaveProperties_p4"),
    ("week1_maxwell.py", "EMWaveProperties_p5"),
    ("week1_maxwell.py", "EMWaveProperties_p6"),
    ("week1_maxwell.py", "EMWaveExample_p1"),
    ("week1_maxwell.py", "EMWaveExample_p2"),
    ("week1_maxwell.py", "EMWaveExample_p3"),
    ("week1_maxwell.py", "EMWaveExample_p4"),
    ("week1_maxwell.py", "EMWaveExample_p5"),
    ("week1_maxwell.py", "EMWaveExample_p6"),
    ("week1_maxwell.py", "PoyntingIrradiance_p1"),
    ("week1_maxwell.py", "PoyntingIrradiance_p2"),
    ("week1_maxwell.py", "PoyntingIrradiance_p3"),
    ("week1_maxwell.py", "PoyntingIrradiance_p4"),
    ("week1_maxwell.py", "PoyntingIrradiance_p5"),
    ("week1_maxwell.py", "PoyntingIrradiance_p6"),
    ("week1_maxwell.py", "PoyntingIrradiance_p7"),
    ("week1_maxwell.py", "PoyntingIrradiance_p8"),
    ("week1_maxwell.py", "PoyntingIrradiance_p9"),
    ("week1_maxwell.py", "PoyntingIrradiance_p10"),
    ("week1_maxwell.py", "RadiationPressure_p1"),
    ("week1_maxwell.py", "RadiationPressure_p2"),
    ("week1_maxwell.py", "RadiationPressure_p3"),
    ("week1_maxwell.py", "RadiationPressure_p4"),
    ("week1_maxwell.py", "RadiationPressure_p5"),
    ("week1_maxwell.py", "RadiationPressure_p6"),
    ("week1_maxwell.py", "RadiationPressure_p7"),
    ("week1_maxwell.py", "RadiationPressure_p8"),
    ("week1_maxwell.py", "DispersionScene_p1"),
    ("week1_maxwell.py", "DispersionScene_p2"),
    ("week1_maxwell.py", "DispersionScene_p3"),
    ("week1_maxwell.py", "DispersionScene_p4"),
    ("week1_maxwell.py", "DispersionScene_p5"),
    ("week1_maxwell.py", "DispersionScene_p6"),
    ("week1_maxwell.py", "DispersionScene_p7"),
    ("week1_maxwell.py", "DispersionScene_p8"),

    # week2_fresnel.py
    ("week2_fresnel.py", "Week2TitleCard_p1"),
    ("week2_fresnel.py", "Week2TitleCard_p2"),
    ("week2_fresnel.py", "Week2TitleCard_p3"),
    ("week2_fresnel.py", "Week2TitleCard_p4"),
    ("week2_fresnel.py", "Week2Intro_p1"),
    ("week2_fresnel.py", "Week2Intro_p2"),
    ("week2_fresnel.py", "Week2Intro_p3"),
    ("week2_fresnel.py", "FermatPrinciple_p1"),
    ("week2_fresnel.py", "FermatPrinciple_p2"),
    ("week2_fresnel.py", "FermatPrinciple_p3"),
    ("week2_fresnel.py", "FermatPrinciple_p4"),
    ("week2_fresnel.py", "ReflectionRefraction_p1"),
    ("week2_fresnel.py", "ReflectionRefraction_p2"),
    ("week2_fresnel.py", "ReflectionRefraction_p3"),
    ("week2_fresnel.py", "ReflectionRefraction_p4"),
    ("week2_fresnel.py", "ReflectionRefraction_p5"),
    ("week2_fresnel.py", "ReflectionRefraction_p6"),
    ("week2_fresnel.py", "ReflectionRefraction_p7"),
    ("week2_fresnel.py", "FresnelEquationsDerivation_p1"),
    ("week2_fresnel.py", "FresnelEquationsDerivation_p2"),
    ("week2_fresnel.py", "FresnelEquationsDerivation_p3"),
    ("week2_fresnel.py", "FresnelEquationsDerivation_p4"),
    ("week2_fresnel.py", "FresnelEquationsDerivation_p5"),
    ("week2_fresnel.py", "FresnelEquationsDerivation_p6"),
    ("week2_fresnel.py", "FresnelEquations_p1"),
    ("week2_fresnel.py", "FresnelEquations_p2"),
    ("week2_fresnel.py", "FresnelEquations_p3"),
    ("week2_fresnel.py", "FresnelEquations_p4"),
    ("week2_fresnel.py", "FresnelEquations_p5"),
    ("week2_fresnel.py", "FresnelEquations_p6"),
    ("week2_fresnel.py", "FresnelEquations_p7"),
    ("week2_fresnel.py", "FresnelEquations_p8"),
    ("week2_fresnel.py", "FresnelEquations_p9"),
    ("week2_fresnel.py", "FresnelEquations_p10"),
    ("week2_fresnel.py", "FresnelFullExample_p1"),
    ("week2_fresnel.py", "FresnelFullExample_p2"),
    ("week2_fresnel.py", "FresnelFullExample_p3"),
    ("week2_fresnel.py", "FresnelFullExample_p4"),
    ("week2_fresnel.py", "FresnelFullExample_p5"),
    ("week2_fresnel.py", "FresnelFullExample_p6"),
    ("week2_fresnel.py", "ReflectivityTransmissivity_p1"),
    ("week2_fresnel.py", "ReflectivityTransmissivity_p2"),
    ("week2_fresnel.py", "ReflectivityTransmissivity_p3"),
    ("week2_fresnel.py", "ReflectivityTransmissivity_p4"),
    ("week2_fresnel.py", "ReflectivityTransmissivity_p5"),
    ("week2_fresnel.py", "BrewsterTIR_p1"),
    ("week2_fresnel.py", "BrewsterTIR_p2"),
    ("week2_fresnel.py", "BrewsterTIR_p3"),
    ("week2_fresnel.py", "BrewsterTIR_p4"),
    ("week2_fresnel.py", "BrewsterTIR_p5"),
    ("week2_fresnel.py", "BrewsterTIR_p6"),
    ("week2_fresnel.py", "BrewsterTIR_p7"),
    ("week2_fresnel.py", "BrewsterTIR_p8"),
    ("week2_fresnel.py", "MalusLaw_p1"),
    ("week2_fresnel.py", "MalusLaw_p2"),
    ("week2_fresnel.py", "MalusLaw_p3"),
    ("week2_fresnel.py", "MalusLaw_p4"),
    ("week2_fresnel.py", "MalusLaw_p5"),
    ("week2_fresnel.py", "MalusLaw_p6"),

    # week3_geometric.py
    ("week3_geometric.py", "Week3TitleCard_p1"),
    ("week3_geometric.py", "Week3TitleCard_p2"),
    ("week3_geometric.py", "Week3TitleCard_p3"),
    ("week3_geometric.py", "Week3TitleCard_p4"),
    ("week3_geometric.py", "GeometricOpticsIntro_p1"),
    ("week3_geometric.py", "GeometricOpticsIntro_p2"),
    ("week3_geometric.py", "GeometricOpticsIntro_p3"),
    ("week3_geometric.py", "GeometricOpticsIntro_p4"),
    ("week3_geometric.py", "GeometricOpticsIntro_p5"),
    ("week3_geometric.py", "SignConventions_p1"),
    ("week3_geometric.py", "SignConventions_p2"),
    ("week3_geometric.py", "SignConventions_p3"),
    ("week3_geometric.py", "SignConventions_p4"),
    ("week3_geometric.py", "SignConventions_p5"),
    ("week3_geometric.py", "SignConventions_p6"),
    ("week3_geometric.py", "SignConventions_p7"),
    ("week3_geometric.py", "SignConventions_p8"),
    ("week3_geometric.py", "SphericalSurface_p1"),
    ("week3_geometric.py", "SphericalSurface_p2"),
    ("week3_geometric.py", "SphericalSurface_p3"),
    ("week3_geometric.py", "SphericalSurface_p4"),
    ("week3_geometric.py", "SphericalSurface_p5"),
    ("week3_geometric.py", "ThinLensScene_p1"),
    ("week3_geometric.py", "ThinLensScene_p2"),
    ("week3_geometric.py", "ThinLensScene_p3"),
    ("week3_geometric.py", "ThinLensScene_p4"),
    ("week3_geometric.py", "ThinLensScene_p5"),
    ("week3_geometric.py", "ThinLensScene_p6"),
    ("week3_geometric.py", "ThinLensScene_p7"),
    ("week3_geometric.py", "ThinLensScene_p8"),
    ("week3_geometric.py", "ThinLensScene_p9"),
    ("week3_geometric.py", "ThinLensScene_p10"),
    ("week3_geometric.py", "ThinLensScene_p11"),
    ("week3_geometric.py", "MirrorScene_p1"),
    ("week3_geometric.py", "MirrorScene_p2"),
    ("week3_geometric.py", "MirrorScene_p3"),
    ("week3_geometric.py", "MirrorScene_p4"),
    ("week3_geometric.py", "MirrorScene_p5"),
    ("week3_geometric.py", "MirrorScene_p6"),
    ("week3_geometric.py", "LensCombinations_p1"),
    ("week3_geometric.py", "LensCombinations_p2"),
    ("week3_geometric.py", "LensCombinations_p3"),
    ("week3_geometric.py", "LensCombinations_p4"),
    ("week3_geometric.py", "LensCombinations_p5"),
    ("week3_geometric.py", "OpticalInstruments_p1"),
    ("week3_geometric.py", "OpticalInstruments_p2"),
    ("week3_geometric.py", "OpticalInstruments_p3"),
    ("week3_geometric.py", "OpticalInstruments_p4"),
    ("week3_geometric.py", "OpticalInstruments_p5"),

    # week4_matrix_polarisation.py
    ("week4_matrix_polarisation.py", "Week4TitleCard_p1"),
    ("week4_matrix_polarisation.py", "Week4TitleCard_p2"),
    ("week4_matrix_polarisation.py", "Week4TitleCard_p3"),
    ("week4_matrix_polarisation.py", "Week4TitleCard_p4"),
    ("week4_matrix_polarisation.py", "Week4TitleCard_p5"),
    ("week4_matrix_polarisation.py", "MatrixOpticsIntro_p1"),
    ("week4_matrix_polarisation.py", "MatrixOpticsIntro_p2"),
    ("week4_matrix_polarisation.py", "MatrixOpticsIntro_p3"),
    ("week4_matrix_polarisation.py", "MatrixOpticsIntro_p4"),
    ("week4_matrix_polarisation.py", "MatrixEquations_p1"),
    ("week4_matrix_polarisation.py", "MatrixEquations_p2"),
    ("week4_matrix_polarisation.py", "MatrixEquations_p3"),
    ("week4_matrix_polarisation.py", "MatrixEquations_p4"),
    ("week4_matrix_polarisation.py", "MatrixEquations_p5"),
    ("week4_matrix_polarisation.py", "SystemMatrixCardinalPoints_p1"),
    ("week4_matrix_polarisation.py", "SystemMatrixCardinalPoints_p2"),
    ("week4_matrix_polarisation.py", "SystemMatrixCardinalPoints_p3"),
    ("week4_matrix_polarisation.py", "SystemMatrixCardinalPoints_p4"),
    ("week4_matrix_polarisation.py", "SystemMatrixCardinalPoints_p5"),
    ("week4_matrix_polarisation.py", "MatrixExample_p1"),
    ("week4_matrix_polarisation.py", "MatrixExample_p2"),
    ("week4_matrix_polarisation.py", "MatrixExample_p3"),
    ("week4_matrix_polarisation.py", "MatrixExample_p4"),
    ("week4_matrix_polarisation.py", "MatrixExample_p5"),
    ("week4_matrix_polarisation.py", "StandingWaves_p1"),
    ("week4_matrix_polarisation.py", "StandingWaves_p2"),
    ("week4_matrix_polarisation.py", "StandingWaves_p3"),
    ("week4_matrix_polarisation.py", "StandingWaves_p4"),
    ("week4_matrix_polarisation.py", "StandingWaves_p5"),
    ("week4_matrix_polarisation.py", "StandingWaves_p6"),
    ("week4_matrix_polarisation.py", "StandingWaves_p7"),
    ("week4_matrix_polarisation.py", "Beating_p1"),
    ("week4_matrix_polarisation.py", "Beating_p2"),
    ("week4_matrix_polarisation.py", "Beating_p3"),
    ("week4_matrix_polarisation.py", "Beating_p4"),
    ("week4_matrix_polarisation.py", "Beating_p5"),
    ("week4_matrix_polarisation.py", "Beating_p6"),
    ("week4_matrix_polarisation.py", "Beating_p7"),
    ("week4_matrix_polarisation.py", "PolarizationBasics_p1"),
    ("week4_matrix_polarisation.py", "PolarizationBasics_p2"),
    ("week4_matrix_polarisation.py", "PolarizationBasics_p3"),
    ("week4_matrix_polarisation.py", "PolarizationBasics_p4"),
    ("week4_matrix_polarisation.py", "PolarizationBasics_p5"),

    # week5_jones.py
    ("week5_jones.py", "Week5TitleCard_p1"),
    ("week5_jones.py", "Week5TitleCard_p2"),
    ("week5_jones.py", "Week5TitleCard_p3"),
    ("week5_jones.py", "Week5TitleCard_p4"),
    ("week5_jones.py", "PolarisationStatesScene_p1"),
    ("week5_jones.py", "PolarisationStatesScene_p2"),
    ("week5_jones.py", "PolarisationStatesScene_p3"),
    ("week5_jones.py", "PolarisationStatesScene_p4"),
    ("week5_jones.py", "PolarisationStatesScene_p5"),
    ("week5_jones.py", "PolarisationStatesScene_p6"),
    ("week5_jones.py", "BirefringenceWavePlates_p1"),
    ("week5_jones.py", "BirefringenceWavePlates_p2"),
    ("week5_jones.py", "BirefringenceWavePlates_p3"),
    ("week5_jones.py", "BirefringenceWavePlates_p4"),
    ("week5_jones.py", "BirefringenceWavePlates_p5"),
    ("week5_jones.py", "BirefringenceWavePlates_p6"),
    ("week5_jones.py", "BirefringenceWavePlates_p7"),
    ("week5_jones.py", "JonesFormalism_p1"),
    ("week5_jones.py", "JonesFormalism_p2"),
    ("week5_jones.py", "JonesFormalism_p3"),
    ("week5_jones.py", "JonesFormalism_p4"),
    ("week5_jones.py", "JonesFormalism_p5"),
    ("week5_jones.py", "JonesFormalism_p6"),
    ("week5_jones.py", "JonesFormalism_p7"),
    ("week5_jones.py", "JonesFormalism_p8"),
    ("week5_jones.py", "JonesMatrices_p1"),
    ("week5_jones.py", "JonesMatrices_p2"),
    ("week5_jones.py", "JonesMatrices_p3"),
    ("week5_jones.py", "JonesMatrices_p4"),
    ("week5_jones.py", "JonesMatrices_p5"),
    ("week5_jones.py", "JonesMatrices_p6"),
    ("week5_jones.py", "JonesMatrices_p7"),
    ("week5_jones.py", "JonesMatrices_p8"),
    ("week5_jones.py", "JonesMatrices_p9"),
    ("week5_jones.py", "JonesMatrices_p10"),
    ("week5_jones.py", "JonesMatrices_p11"),

    # week6_interference.py
    ("week6_interference.py", "Week6TitleCard_p1"),
    ("week6_interference.py", "Week6TitleCard_p2"),
    ("week6_interference.py", "Week6TitleCard_p3"),
    ("week6_interference.py", "Week6TitleCard_p4"),
    ("week6_interference.py", "InterferenceIntroScene_p1"),
    ("week6_interference.py", "InterferenceIntroScene_p2"),
    ("week6_interference.py", "InterferenceIntroScene_p3"),
    ("week6_interference.py", "InterferenceIntroScene_p4"),
    ("week6_interference.py", "InterferenceIntroScene_p5"),
    ("week6_interference.py", "TwoBeamInterference_p1"),
    ("week6_interference.py", "TwoBeamInterference_p2"),
    ("week6_interference.py", "TwoBeamInterference_p3"),
    ("week6_interference.py", "TwoBeamInterference_p4"),
    ("week6_interference.py", "TwoBeamInterference_p5"),
    ("week6_interference.py", "YoungDoubleSlit_p1"),
    ("week6_interference.py", "YoungDoubleSlit_p2"),
    ("week6_interference.py", "YoungDoubleSlit_p3"),
    ("week6_interference.py", "YoungDoubleSlit_p4"),
    ("week6_interference.py", "YoungDoubleSlit_p5"),
    ("week6_interference.py", "YoungDoubleSlit_p6"),
    ("week6_interference.py", "YoungDoubleSlit_p7"),
    ("week6_interference.py", "ThinFilmInterference_p1"),
    ("week6_interference.py", "ThinFilmInterference_p2"),
    ("week6_interference.py", "ThinFilmInterference_p3"),
    ("week6_interference.py", "ThinFilmInterference_p4"),
    ("week6_interference.py", "ThinFilmInterference_p5"),
    ("week6_interference.py", "ThinFilmInterference_p6"),
    ("week6_interference.py", "ThinFilmInterference_p7"),
    ("week6_interference.py", "ThinFilmInterference_p8"),
    ("week6_interference.py", "ThinFilmInterference_p9"),
    ("week6_interference.py", "ThinFilmInterference_p10"),
    ("week6_interference.py", "FringeVisibility_p1"),
    ("week6_interference.py", "FringeVisibility_p2"),
    ("week6_interference.py", "FringeVisibility_p3"),
    ("week6_interference.py", "FringeVisibility_p4"),
    ("week6_interference.py", "FringeVisibility_p5"),
    ("week6_interference.py", "MichelsonScene_p1"),
    ("week6_interference.py", "MichelsonScene_p2"),
    ("week6_interference.py", "MichelsonScene_p3"),
    ("week6_interference.py", "MichelsonScene_p4"),
    ("week6_interference.py", "MichelsonScene_p5"),

    # week7_diffraction.py
    ("week7_diffraction.py", "Week7TitleCard_p1"),
    ("week7_diffraction.py", "Week7TitleCard_p2"),
    ("week7_diffraction.py", "Week7TitleCard_p3"),
    ("week7_diffraction.py", "Week7TitleCard_p4"),
    ("week7_diffraction.py", "HuygensPrinciple_p1"),
    ("week7_diffraction.py", "HuygensPrinciple_p2"),
    ("week7_diffraction.py", "HuygensPrinciple_p3"),
    ("week7_diffraction.py", "HuygensPrinciple_p4"),
    ("week7_diffraction.py", "SingleSlitDiffraction_p1"),
    ("week7_diffraction.py", "SingleSlitDiffraction_p2"),
    ("week7_diffraction.py", "SingleSlitDiffraction_p3"),
    ("week7_diffraction.py", "SingleSlitDiffraction_p4"),
    ("week7_diffraction.py", "SingleSlitDiffraction_p5"),
    ("week7_diffraction.py", "SingleSlitDiffraction_p6"),
    ("week7_diffraction.py", "SingleSlitDiffraction_p7"),
    ("week7_diffraction.py", "CircularApertureRayleigh_p1"),
    ("week7_diffraction.py", "CircularApertureRayleigh_p2"),
    ("week7_diffraction.py", "CircularApertureRayleigh_p3"),
    ("week7_diffraction.py", "CircularApertureRayleigh_p4"),
    ("week7_diffraction.py", "CircularApertureRayleigh_p5"),
    ("week7_diffraction.py", "CircularApertureRayleigh_p6"),
    ("week7_diffraction.py", "CircularApertureRayleigh_p7"),
    ("week7_diffraction.py", "DiffractionGrating_p1"),
    ("week7_diffraction.py", "DiffractionGrating_p2"),
    ("week7_diffraction.py", "DiffractionGrating_p3"),
    ("week7_diffraction.py", "DiffractionGrating_p4"),
    ("week7_diffraction.py", "DiffractionGrating_p5"),
    ("week7_diffraction.py", "DiffractionGrating_p6"),
    ("week7_diffraction.py", "DiffractionGrating_p7"),

    # week8_fabry_perot.py
    ("week8_fabry_perot.py", "Week8TitleCard_p1"),
    ("week8_fabry_perot.py", "Week8TitleCard_p2"),
    ("week8_fabry_perot.py", "Week8TitleCard_p3"),
    ("week8_fabry_perot.py", "Week8TitleCard_p4"),
    ("week8_fabry_perot.py", "MultiBeamIntro_p1"),
    ("week8_fabry_perot.py", "MultiBeamIntro_p2"),
    ("week8_fabry_perot.py", "MultiBeamIntro_p3"),
    ("week8_fabry_perot.py", "MultiBeamIntro_p4"),
    ("week8_fabry_perot.py", "AiryFunction_p1"),
    ("week8_fabry_perot.py", "AiryFunction_p2"),
    ("week8_fabry_perot.py", "AiryFunction_p3"),
    ("week8_fabry_perot.py", "AiryFunction_p4"),
    ("week8_fabry_perot.py", "AiryFunction_p5"),
    ("week8_fabry_perot.py", "FinesseResolving_p1"),
    ("week8_fabry_perot.py", "FinesseResolving_p2"),
    ("week8_fabry_perot.py", "FinesseResolving_p3"),
    ("week8_fabry_perot.py", "FinesseResolving_p4"),
    ("week8_fabry_perot.py", "FinesseResolving_p5"),
    ("week8_fabry_perot.py", "FinesseResolving_p6"),
    ("week8_fabry_perot.py", "FabryPerotExample_p1"),
    ("week8_fabry_perot.py", "FabryPerotExample_p2"),
    ("week8_fabry_perot.py", "FabryPerotExample_p3"),
    ("week8_fabry_perot.py", "FabryPerotExample_p4"),
    ("week8_fabry_perot.py", "FabryPerotExample_p5"),
    ("week8_fabry_perot.py", "FabryPerotExample_p6"),
    ("week8_fabry_perot.py", "FabryPerotExample_p7"),
    ("week8_fabry_perot.py", "FabryPerotExample_p8"),
    ("week8_fabry_perot.py", "CoherenceLength_p1"),
    ("week8_fabry_perot.py", "CoherenceLength_p2"),
    ("week8_fabry_perot.py", "CoherenceLength_p3"),
    ("week8_fabry_perot.py", "CoherenceLength_p4"),
    ("week8_fabry_perot.py", "CoherenceLength_p5"),
    ("week8_fabry_perot.py", "CoherenceLength_p6"),
    ("week8_fabry_perot.py", "CoherenceLength_p7"),
    ("week8_fabry_perot.py", "Week8Summary_p1"),
    ("week8_fabry_perot.py", "Week8Summary_p2"),
    ("week8_fabry_perot.py", "Week8Summary_p3"),
    ("week8_fabry_perot.py", "Week8Summary_p4"),
    ("week8_fabry_perot.py", "Week8Summary_p5"),
    ("week8_fabry_perot.py", "Week8Summary_p6"),
    ("week8_fabry_perot.py", "Week8Summary_p7"),
    ("week8_fabry_perot.py", "Week8Summary_p8"),

    # formula_sheet_recap.py
    ("formula_sheet_recap.py", "FormulaSheetTitleCard_p1"),
    ("formula_sheet_recap.py", "FormulaSheetTitleCard_p2"),
    ("formula_sheet_recap.py", "FormulaSheetTitleCard_p3"),
    ("formula_sheet_recap.py", "MidtermPrepScene_p1"),
    ("formula_sheet_recap.py", "MidtermPrepScene_p2"),
    ("formula_sheet_recap.py", "MidtermPrepScene_p3"),
    ("formula_sheet_recap.py", "MidtermPrepScene_p4"),
    ("formula_sheet_recap.py", "MidtermPrepScene_p5"),
    ("formula_sheet_recap.py", "FinalExamPrepScene_p1"),
    ("formula_sheet_recap.py", "FinalExamPrepScene_p2"),
    ("formula_sheet_recap.py", "FinalExamPrepScene_p3"),
    ("formula_sheet_recap.py", "FinalExamPrepScene_p4"),
    ("formula_sheet_recap.py", "FinalExamPrepScene_p5"),

    # exercises_week1.py
    ("exercises_week1.py", "SC_Week1_Problem1"),
    ("exercises_week1.py", "SC_Week1_Problem2"),
    ("exercises_week1.py", "SC_Week1_Problem3"),
    ("exercises_week1.py", "SC_Week1_Problem4"),
    ("exercises_week1.py", "SC_Week1_Problem5"),

    # exercises_week2.py
    ("exercises_week2.py", "SC_Week2_Problem1"),
    ("exercises_week2.py", "SC_Week2_Problem2"),
    ("exercises_week2.py", "SC_Week2_Problem6"),
    ("exercises_week2.py", "SC_Week2_Problem7"),

    # exercises_week3.py
    ("exercises_week3.py", "SC_Week3_Problem1"),
    ("exercises_week3.py", "SC_Week3_Problem3"),

    # exercises_week4.py
    ("exercises_week4.py", "SC_Week4_Problem1"),
    ("exercises_week4.py", "SC_Week4_Problem3"),

    # exercises_week5.py
    ("exercises_week5.py", "SC_Week5_Problem3"),
    ("exercises_week5.py", "SC_Week5_Problem4"),
    ("exercises_week5.py", "SC_Week5_Problem7"),

    # exercises_week6.py
    ("exercises_week6.py", "SC_Week6_Problem1"),
    ("exercises_week6.py", "SC_Week6_Problem3"),
    ("exercises_week6.py", "SC_Week6_Problem4"),

    # exercises_week7.py
    ("exercises_week7.py", "SC_Week7_Problem1"),
    ("exercises_week7.py", "SC_Week7_Problem5"),
    ("exercises_week7.py", "SC_Week7_Problem10"),

    # exercises_week8.py
    ("exercises_week8.py", "SC_Week8_Problem3"),
    ("exercises_week8.py", "SC_Week8_Problem9"),
    ("exercises_week8.py", "SC_Week8_Problem10"),

    # slt_week1.py
    ("slt_week1.py", "SLT_Week1_Problem1"),
    ("slt_week1.py", "SLT_Week1_Problem2"),

    # slt_week2.py
    ("slt_week2.py", "SLT_Week2_Problem1"),
    ("slt_week2.py", "SLT_Week2_Problem2"),

    # slt_week3.py
    ("slt_week3.py", "SLT_Week3_Problem1"),

    # slt_week5.py
    ("slt_week5.py", "SLT_Week5_Problem1"),

    # slt_week6.py
    ("slt_week6.py", "SLT_Week6_Problem1"),
    ("slt_week6.py", "SLT_Week6_Problem2"),
    ("slt_week6.py", "SLT_Week6_Problem3"),

    # slt_week7.py
    ("slt_week7.py", "SLT_Week7_Problem1"),
    ("slt_week7.py", "SLT_Week7_Problem2"),

    # slt_week8.py
    ("slt_week8.py", "SLT_Week8_Problem1"),
    ("slt_week8.py", "SLT_Week8_Problem2"),

    # slt_week9.py
    ("slt_week9.py", "SLT_Week9_Problem1"),
    ("slt_week9.py", "SLT_Week9_Problem2"),
    ("slt_week9.py", "SLT_Week9_Problem4"),
]


QUALITY_FLAG = "qh"   # qh = 1080p60 | ql = 480p15 (low for testing) | qm = 720p


def print_render_commands(quality: str = QUALITY_FLAG) -> None:
    """Print all manim render commands in order."""
    print(f"# 31OPT Optics — {len(RENDER_ORDER)} scenes to render")
    print(f"# Quality: -{quality}   Change QUALITY_FLAG in main.py to 'ql' for fast preview")
    print()
    for filepath, scene in RENDER_ORDER:
        if Path(filepath).exists():
            print(f"python -m manim -{quality} {filepath} {scene}")
        else:
            print(f"# MISSING FILE: {filepath}  (scene: {scene})")


def print_filelist(quality: str = QUALITY_FLAG) -> None:
    """Print ffmpeg concat filelist for all rendered scenes."""
    res = "1080p60" if quality == "qh" else ("480p15" if quality == "ql" else "720p30")
    for filepath, scene in RENDER_ORDER:
        stem = Path(filepath).stem
        mp4  = Path(f"media/videos/{stem}/{res}/{scene}.mp4")
        if mp4.exists():
            print(f"file '{mp4}'")
        else:
            print(f"# NOT YET RENDERED: {mp4}")


def print_scenes() -> None:
    """Print all scene names grouped by file."""
    current_file = None
    for filepath, scene in RENDER_ORDER:
        if filepath != current_file:
            current_file = filepath
            print(f"\n── {filepath} ──")
        print(f"    {scene}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="31OPT Optics Manim render helper")
    parser.add_argument("--list",      action="store_true", help="Print all render commands")
    parser.add_argument("--filelist",  action="store_true", help="Print ffmpeg concat filelist")
    parser.add_argument("--scenes",    action="store_true", help="List all scene names")
    parser.add_argument("--quality",   default=QUALITY_FLAG, help="Manim quality flag (qh/qm/ql)")
    args = parser.parse_args()

    if args.filelist:
        print_filelist(args.quality)
    elif args.scenes:
        print_scenes()
    else:
        print_render_commands(args.quality)
