"""
screen_content.py — defines what appears ON SCREEN for each paragraph.
Narration text is spoken by TTS. Screen shows LaTeX equation + short caption.

Format per scene: list of (latex_string_or_None, short_caption_string)
One entry per narration paragraph, in order.
"""

SC = {

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 1 — WAVES
# ═══════════════════════════════════════════════════════════════════════════════
'Week1TitleCard': [
    (None, "31OPT Optics — complete exam preparation series"),
    (None, "Weeks 1-8 covered in full from Bennett 2nd edition"),
    (None, "Theory: derivations, examples and physical intuition"),
    (None, "Start with the most fundamental question: what is a wave?"),
],
'WaveIntroduction': [
    (None, "A wave propagates energy without transporting matter"),
    (None, "Ocean: water stays put, disturbance moves — same principle"),
    (None, "Sound: air molecules oscillate, compression wave propagates"),
    (None, "EM waves: E and B fields oscillate — no medium needed"),
    (None, "1D wave equation captures all essential wave physics"),
    (None, "Wave function psi(x,t): physical quantity at position x, time t"),
],
'WaveEquation1D': [
    (r'\frac{\partial^2\Psi}{\partial x^2}=\frac{1}{v^2}\frac{\partial^2\Psi}{\partial t^2}',
     "The 1D wave equation  (Bennett Eq. 1.1)"),
    (r'\frac{\partial^2\Psi}{\partial x^2}',
     "LEFT SIDE — spatial curvature of the wave profile"),
    (r'\frac{1}{v^2}\frac{\partial^2\Psi}{\partial t^2}',
     "RIGHT SIDE — temporal acceleration / v²"),
    (None, "Curvature in space proportional to acceleration in time"),
    (None, "Linear equation — superposition principle holds exactly"),
    (r'\Psi = f(x-vt)\;\text{or}\;g(x+vt)',
     "General solution: any shape, speed v, either direction"),
    (None, "f(x-vt) moves right rigidly at speed v"),
    (None, "Shape preservation holds only in non-dispersive media"),
],
'WaveEquationProof': [
    (r'\Psi=(x-vt)^2\quad\text{— test this in the wave equation}',
     "Choose the quadratic as a concrete test function"),
    (r'\frac{\partial^2\Psi}{\partial x^2}=2 \qquad \frac{\partial^2\Psi}{\partial t^2}=2v^2',
     "Both second derivatives computed explicitly"),
    (r'\frac{2}{v^2\cdot 2}=\frac{1}{v^2}\;\checkmark',
     "Ratio gives 1/v² — wave equation satisfied"),
    (r'\frac{\partial^2 f}{\partial x^2}=f^{\prime\prime}\qquad\frac{\partial^2 f}{\partial t^2}=v^2 f^{\prime\prime}',
     "General proof for any f(x-vt) via chain rule"),
    (None, "Any twice-differentiable function is a valid wave solution"),
],
'HarmonicWave': [
    (None, "Harmonic wave: single-frequency sinusoidal oscillation"),
    (r'\Psi(x,t)=A\sin(kx-\omega t+\phi)',
     "The harmonic traveling wave  (Bennett Eq. 1.14)"),
    (None, "Every symbol in this equation recurs throughout the course"),
    (r'A', "AMPLITUDE — maximum value  [V/m for E-field]  |  I \u221d A\u00b2"),
    (r'k=\frac{2\pi}{\lambda}', "WAVE NUMBER — spatial frequency  [rad/m]"),
    (r'\omega=2\pi f=\frac{2\pi}{T}', "ANGULAR FREQUENCY  [rad/s]"),
    (r'\lambda', "WAVELENGTH — distance between adjacent crests  [m]"),
    (r'f=\frac{1}{T}', "FREQUENCY — cycles per second  [Hz]"),
    (r'v=\frac{\omega}{k}=f\lambda', "PHASE SPEED — speed of crests  [m/s]"),
    (r'\phi', "INITIAL PHASE — shifts wave in time  [rad]"),
    (r'v=f\lambda \quad k=\frac{2\pi}{\lambda} \quad \omega=2\pi f \quad T=\frac{1}{f}',
     "FIVE KEY RELATIONS — memorise all of them"),
    (None, "Worked example: lambda = 500 nm visible light in vacuum"),
    (r'k=1.257\times10^7\,\mathrm{rad/m} \qquad f=5.996\times10^{14}\,\mathrm{Hz}',
     "Wave number and frequency for 500 nm"),
    (r'\omega=3.768\times10^{15}\,\mathrm{rad/s} \qquad T=1.668\,\mathrm{fs}',
     "Period = 1.668 femtoseconds"),
    (None, "T = 1.668 fs: a million times shorter than a nanosecond"),
    (r'\Psi=E_0\sin(1.257\times10^7 x-3.768\times10^{15}t+\phi)',
     "Complete wave function for 500 nm E-field"),
    (None, "Any wave decomposes into harmonic components — Fourier"),
],
'HarmonicWaveExample': [
    (r'\lambda=632.8\,\mathrm{nm} \quad v=c=2.998\times10^8\,\mathrm{m/s}',
     "He-Ne laser — given quantities"),
    (r'k=9.926\times10^6\,\mathrm{rad/m} \quad f=4.738\times10^{14}\,\mathrm{Hz}',
     "Wave number and frequency"),
    (r'\omega=2.977\times10^{15}\,\mathrm{rad/s} \quad T=2.11\,\mathrm{fs}',
     "Angular frequency and period"),
    (r'E_x=E_0\sin(9.926\times10^6\,z-2.977\times10^{15}\,t)',
     "Complete E-field wave function"),
    (None, "2.11 fs period: one million times shorter than a nanosecond"),
    (None, "632.8 nm is about 1/100 the diameter of a human hair"),
    (r'I=\tfrac{1}{2}\varepsilon_0 c E_0^2=1327\,\mathrm{W/m^2}\;\text{for }E_0=1000\,\mathrm{V/m}',
     "Irradiance from amplitude  (Bennett Eq. 2.33)"),
    (None, "I proportional to A squared — doubling field quadruples intensity"),
    (None, "Optical period too short for any electronic detection"),
    (None, "All optical detectors measure intensity, not field phase"),
],
'SuperpositionPrinciple': [
    (None, "Superposition principle  (Bennett Section 1.5)"),
    (r'\frac{\partial^2(\Psi_1+\Psi_2)}{\partial x^2}=\frac{1}{v^2}\frac{\partial^2(\Psi_1+\Psi_2)}{\partial t^2}\;\checkmark',
     "Proof: sum of solutions satisfies wave equation"),
    (None, "Any linear combination a psi-1 + b psi-2 is also a solution"),
    (None, "Two laser beams cross in space without affecting each other"),
    (None, "Foundation of ALL interference and diffraction  (Weeks 6-7)"),
    (None, "Fails at high intensity in nonlinear media — frequency doubling"),
],
'PhaseGroupVelocity': [
    (None, "Two distinct velocities associated with any dispersive wave"),
    (r'v_p=\frac{\omega}{k}', "PHASE VELOCITY — speed of individual crests"),
    (r'v_g=\frac{d\omega}{dk}', "GROUP VELOCITY — speed of energy and information"),
    (None, "Vacuum: omega = ck, so vp = vg = c — no dispersion"),
    (r'v_g=\frac{c}{n+\omega\,dn/d\omega}', "Group velocity in dispersive medium  (Bennett 7.7)"),
    (None, "Normal dispersion: dn/d-omega > 0 so vg < c/n — energy slower than crests"),
    (r'\omega=ak^2 \;\Rightarrow\; v_p=ak,\quad v_g=2ak=2v_p',
     "Dispersive example: group speed = 2 x phase speed"),
    (None, "Water waves: envelope travels at half the crest speed"),
],
'ComplexRepresentation': [
    (None, "Complex notation replaces trig with exponentials  (Bennett 1.6)"),
    (r'e^{i\theta}=\cos\theta+i\sin\theta',
     "Euler's formula — foundation of complex wave notation"),
    (r'\cos\theta=\mathrm{Re}[e^{i\theta}] \qquad \sin\theta=\mathrm{Im}[e^{i\theta}]',
     "Cosine = real part, sine = imaginary part"),
    (r'\tilde{\Psi}=Ae^{i(kx-\omega t)} \quad \Psi_\mathrm{phys}=\mathrm{Re}[\tilde{\Psi}]',
     "Complex wave — physical wave is real part"),
    (r'|\tilde{\Psi}|^2=\tilde{\Psi}\cdot\tilde{\Psi}^*=A^2',
     "Intensity proportional to modulus squared = A squared"),
    (r'|\tilde{\Psi}_1+\tilde{\Psi}_2|^2=A_1^2+A_2^2+2\mathrm{Re}[\tilde{\Psi}_1\tilde{\Psi}_2^*]',
     "Cross term = interference term"),
    (r'\tilde{\Psi}_{3D}=Ae^{i(\mathbf{k}\cdot\mathbf{r}-\omega t)}',
     "3D plane wave — wavefronts perpendicular to k"),
    (r'\tilde{\Psi}_\mathrm{sph}=\frac{A}{r}e^{i(kr-\omega t)}',
     "Spherical wave — amplitude 1/r, intensity 1/r squared"),
    (None, "Inverse square law follows from energy conservation"),
],
'ThreeDWaves': [
    (r'\nabla^2\Psi=\frac{1}{v^2}\frac{\partial^2\Psi}{\partial t^2}',
     "3D wave equation  (Bennett Section 1.7)"),
    (r'\tilde{\Psi}=Ae^{i(\mathbf{k}\cdot\mathbf{r}-\omega t)} \quad |\mathbf{k}|=\frac{2\pi}{\lambda}',
     "3D plane wave — k-vector in propagation direction"),
    (r'\tilde{\Psi}=\frac{A}{r}e^{i(kr-\omega t)} \quad I\propto\frac{1}{r^2}',
     "Spherical wave — inverse square law"),
    (r'\mathbf{k}=k_x\hat{x}+k_y\hat{y}+k_z\hat{z}',
     "Wave vector components in 3D"),
],
'Week1WavesSummary': [
    (None, "Week 1a complete — collect key results"),
    (r'\frac{\partial^2\Psi}{\partial x^2}=\frac{1}{v^2}\frac{\partial^2\Psi}{\partial t^2} \quad \Psi=f(x\pm vt)',
     "Wave equation and general solution"),
    (r'v=f\lambda=\frac{\omega}{k} \quad k=\frac{2\pi}{\lambda} \quad \omega=2\pi f \quad T=\frac{1}{f}',
     "Five harmonic wave relations"),
    (r'\tilde{\Psi}=Ae^{i(kx-\omega t)} \quad I\propto|\tilde{\Psi}|^2=A^2',
     "Complex representation and intensity"),
    (r'v_p=\frac{\omega}{k} \quad v_g=\frac{d\omega}{dk}',
     "Phase velocity vs group velocity"),
    (r'\tilde{\Psi}_{3D}=Ae^{i(\mathbf{k}\cdot\mathbf{r}-\omega t)}',
     "3D plane wave — general form"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 1b — MAXWELL
# ═══════════════════════════════════════════════════════════════════════════════
'MaxwellIntro': [
    (None, "Maxwell's equations — four laws of classical EM  (Bennett Ch. 2)"),
    (None, "Unified electricity, magnetism and optics in 1865"),
    (None, "All optics topics derive from these four equations"),
    (None, "Differential form used throughout this course"),
],
'VectorCalculusNotation': [
    (r'\nabla\phi=\left(\frac{\partial\phi}{\partial x},\frac{\partial\phi}{\partial y},\frac{\partial\phi}{\partial z}\right)',
     "GRADIENT — direction and rate of steepest increase"),
    (r'\nabla\cdot\mathbf{F}=\frac{\partial F_x}{\partial x}+\frac{\partial F_y}{\partial y}+\frac{\partial F_z}{\partial z}',
     "DIVERGENCE — sources (+) and sinks (−) of field"),
    (r'\nabla\times\mathbf{F}',
     "CURL — rotation of field around a point"),
    (r'\nabla^2\phi=\frac{\partial^2\phi}{\partial x^2}+\frac{\partial^2\phi}{\partial y^2}+\frac{\partial^2\phi}{\partial z^2}',
     "LAPLACIAN — curvature / deviation from neighbourhood average"),
    (None, "These operators appear in every Maxwell equation"),
],
'MaxwellEquations': [
    (r'\nabla\cdot\mathbf{E}=\rho_\mathrm{free}/\varepsilon',
     "Gauss's Law — charges are sources of E field"),
    (r'\nabla\cdot\mathbf{B}=0',
     "No magnetic monopoles — B field lines always closed loops"),
    (r'\nabla\times\mathbf{E}=-\partial\mathbf{B}/\partial t',
     "Faraday's Law — changing B creates curling E"),
    (r'\nabla\times\mathbf{B}=\mu(\mathbf{J}+\varepsilon\,\partial\mathbf{E}/\partial t)',
     "Ampere-Maxwell Law — currents AND changing E create B"),
    (None, "Displacement current term (epsilon dE/dt) was Maxwell's key insight"),
    (r'\nabla\cdot\mathbf{E}=0\quad\nabla\cdot\mathbf{B}=0\quad\text{(vacuum, no sources)}',
     "In vacuum with no charges/currents — both divergences zero"),
    (r'\nabla^2\mathbf{E}=\mu_0\varepsilon_0\,\partial^2\mathbf{E}/\partial t^2 \quad v=1/\sqrt{\mu_0\varepsilon_0}=c',
     "Wave equation for E — speed = c"),
],
'MaxwellVacuum': [
    (r'\nabla\cdot\mathbf{E}=0\quad\nabla\cdot\mathbf{B}=0',
     "In vacuum: no sources, no divergence"),
    (r'\nabla\times\mathbf{E}=-\frac{\partial\mathbf{B}}{\partial t}\qquad\nabla\times\mathbf{B}=\mu_0\varepsilon_0\frac{\partial\mathbf{E}}{\partial t}',
     "Coupled curl equations — fields sustain each other"),
    (r'\nabla^2\mathbf{E}=\mu_0\varepsilon_0\frac{\partial^2\mathbf{E}}{\partial t^2}',
     "EM wave equation for E in vacuum"),
    (None, "E determines B and vice versa — fields are coupled"),
],
'EMWaveDerivation': [
    (None, "Derivation of EM wave equation from Maxwell's equations"),
    (r'\nabla\times(\nabla\times\mathbf{E})=-\frac{\partial}{\partial t}(\nabla\times\mathbf{B})=-\mu_0\varepsilon_0\frac{\partial^2\mathbf{E}}{\partial t^2}',
     "Take curl of Faraday, substitute Ampere-Maxwell"),
    (r'\nabla^2\mathbf{E}=\mu_0\varepsilon_0\frac{\partial^2\mathbf{E}}{\partial t^2} \quad c=\frac{1}{\sqrt{\mu_0\varepsilon_0}}',
     "EM wave equation — wave speed = c"),
    (r'c=\frac{1}{\sqrt{4\pi\times10^{-7}\times8.854\times10^{-12}}}=2.998\times10^8\,\mathrm{m/s}',
     "Maxwell computed c from EM measurements alone"),
    (None, "Agreement with measured speed of light identified light as EM wave"),
],
'EMWaveProperties': [
    (r'\mathbf{k}\perp\mathbf{E}\perp\mathbf{B}',
     "E, B and k all mutually perpendicular — transverse wave"),
    (r'\mathbf{B}=\frac{\hat{k}\times\mathbf{E}}{v}',
     "B determined by E and propagation direction"),
    (r'E=cB\quad\text{in vacuum}',
     "Magnitudes related by E = cB"),
    (None, "E and B oscillate in phase — both peak simultaneously"),
    (r'v=c/n\quad\lambda_\mathrm{medium}=\lambda_0/n',
     "In medium n: speed c/n, wavelength lambda/n, frequency unchanged"),
    (None, "Frequency unchanged at interface — only wavelength changes"),
],
'EMWaveExample': [
    (r'\mathbf{E}=E_0\hat{x}\,e^{i(kz-\omega t)}\quad\text{— find }\mathbf{B}',
     "Given E in x-direction, propagating in z — find B"),
    (r'\mathbf{B}=\frac{\hat{z}\times\hat{x}}{c}E_0\,e^{i(kz-\omega t)}=\frac{E_0}{c}\hat{y}\,e^{i(kz-\omega t)}',
     "B in y-direction  (z-hat cross x-hat = y-hat)"),
    (r'\mathbf{E}\perp\mathbf{B}\perp\hat{k}\quad\hat{x}\perp\hat{y}\perp\hat{z}\;\checkmark',
     "All perpendicularity conditions verified"),
    (r'I=\tfrac{1}{2}\varepsilon_0 c E_0^2=1327\,\mathrm{W/m^2}',
     "Irradiance for E0 = 1000 V/m  (Bennett Eq. 2.33)"),
    (None, "Full verification: transverse, orthogonal, E=cB, in-phase"),
    (None, "Practice this calculation until it takes under 2 minutes"),
],
'PoyntingIrradiance': [
    (r'\mathbf{S}=\frac{1}{\mu_0}\mathbf{E}\times\mathbf{B}',
     "Poynting vector — energy flux  [W/m²]  (Bennett 2.3.1)"),
    (r'I=\langle|\mathbf{S}|\rangle=\frac{1}{2}\varepsilon_0 c n E_0^2',
     "Irradiance = time-averaged Poynting magnitude  (Bennett Eq. 2.33)"),
    (None, "Factor of 1/2 from time-averaging cos²(omega t) over one period"),
    (None, "Irradiance proportional to E0 squared — doubling field quadruples I"),
    (r'I=5\times10^{-3}/(\pi\times10^{-6})=1592\,\mathrm{W/m^2}',
     "Example: 5 mW laser focused to 1 mm radius spot"),
    (r'E_0=\sqrt{2I/(\varepsilon_0 c)}=1095\,\mathrm{V/m}',
     "Peak E-field in the beam"),
    (r'B_0=E_0/c=3.65\,\mu\mathrm{T}',
     "Peak B-field — 14x weaker than Earth's field"),
    (None, "Yet oscillating at 500 THz — no electronic circuit can follow"),
    (r'P_\mathrm{rad}=I/c\;(\text{absorber})\quad 2I/c\;(\text{mirror})',
     "Radiation pressure on absorber vs perfect mirror"),
    (None, "Solar irradiance 1361 W/m² gives 9 microPascals on a mirror"),
],
'RadiationPressure': [
    (None, "Light carries momentum — Maxwell predicted, Lebedev measured 1900"),
    (r'P_\mathrm{rad}=I/c\;(\text{absorber})',
     "Radiation pressure on perfect absorber"),
    (r'P_\mathrm{rad}=2I/c\;(\text{mirror})',
     "Radiation pressure on perfect mirror — momentum reverses"),
    (r'P_\mathrm{rad}=\frac{I(1+R)}{c}',
     "General: reflectivity R between 0 and 1"),
    (None, "Solar sail: 1 mN thrust from 14 x 14 m sail — IKAROS 2010"),
    (None, "Optical tweezers: trap cells with focused laser gradient force"),
    (None, "Nobel Prize 2018: Arthur Ashkin — optical tweezers"),
    (None, "LIGO: 100 kW intracavity power — radiation pressure must be managed"),
],
'DispersionScene': [
    (None, "Dispersion: refractive index depends on frequency  (Bennett 3.9)"),
    (r'n=c/v_p\quad\text{— depends on frequency in dispersive media}',
     "Index n = c/vp — varies with omega in glass"),
    (None, "Normal dispersion: n increases with frequency — violet refracts more"),
    (None, "Lorentz model: electrons as bound oscillators driven by light field"),
    (r'v_g=\frac{c}{n+\omega\,dn/d\omega}',
     "Group velocity — energy travels at vg, not vp"),
    (None, "Anomalous dispersion near resonance: dn/domega < 0"),
    (None, "Pulse broadening in optical fibres: 17 ps/nm/km at 1550 nm"),
    (None, "Dispersion-compensating fibres reverse broadening for higher data rates"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 2 — FRESNEL
# ═══════════════════════════════════════════════════════════════════════════════
'Week2TitleCard': [
    (None, "Week 2: what happens when light hits an interface"),
    (None, "Snell's law for direction — Fresnel equations for amplitude"),
    (None, "Every lens, mirror coating and optical fibre depends on this"),
    (None, "Bennett Chapter 3 — Reflection and Refraction"),
],
'Week2Intro': [
    (None, "Even transparent glass reflects ~4% from each surface"),
    (None, "Derived from Maxwell's boundary conditions at the interface"),
    (r'\text{s-pol: }\mathbf{E}\perp\text{plane of incidence}\quad\text{p-pol: }\mathbf{E}\parallel\text{plane}',
     "S and P polarisations interact differently with interface"),
    (None, "Frequency unchanged at interface — only wavelength and speed change"),
],
'FermatPrinciple': [
    (None, "Fermat's principle: light takes the path of stationary travel time"),
    (None, "Reflection: minimise total path length — gives angle in = angle out"),
    (r'n_i\sin\theta_i=n_t\sin\theta_t',
     "Refraction: minimise time with different speeds — gives Snell's law"),
    (None, "Fermat connects optics to variational mechanics (Hamilton, Feynman)"),
],
'ReflectionRefraction': [
    (r'\theta_i=\theta_r',
     "Law of reflection — angle in equals angle out"),
    (r'n_i\sin\theta_i=n_t\sin\theta_t',
     "Snell's Law  (Bennett Eq. 3.2)"),
    (None, "n increases: refracted beam bends toward normal"),
    (None, "n decreases: refracted beam bends away from normal"),
    (None, "Frequency fixed — wavelength = lambda0/n in medium"),
    (r'\text{Example: }n_i=1.5,\;\theta_i=30°\;\Rightarrow\;\theta_t=48.6°',
     "Glass to air — beam bends away from normal"),
    (r'\text{At }\theta_i=41.8°:\;\sin\theta_t=1.000\;\Rightarrow\;\text{TIR}',
     "Critical angle reached — total internal reflection"),
    (None, "No transmitted beam exists above the critical angle"),
],
'FresnelEquationsDerivation': [
    (None, "Fresnel equations from Maxwell boundary conditions  (Bennett 3.3)"),
    (None, "Tangential E and tangential H continuous across interface"),
    (None, "S-polarisation: E already tangential, simple boundary condition"),
    (r'E_i+E_r=E_t\quad n_i\cos\theta_i(E_i-E_r)=n_t\cos\theta_t\,E_t',
     "Two equations for s-pol give r-s and t-s"),
    (None, "P-polarisation: extra cosine factors from geometry"),
    (None, "S and P components reflect independently with different coefficients"),
],
'FresnelEquations': [
    (None, "Fresnel equations: amplitude reflection and transmission coefficients"),
    (r'r_\perp=\frac{n_i\cos\theta_i-n_t\cos\theta_t}{n_i\cos\theta_i+n_t\cos\theta_t}',
     "s-polarisation reflection coefficient  (Bennett Eq. 3.11a)"),
    (r't_\perp=\frac{2n_i\cos\theta_i}{n_i\cos\theta_i+n_t\cos\theta_t}',
     "s-polarisation transmission coefficient  (Bennett Eq. 3.12a)"),
    (r'r_\parallel=\frac{n_t\cos\theta_i-n_i\cos\theta_t}{n_t\cos\theta_i+n_i\cos\theta_t}',
     "p-polarisation reflection coefficient  (Bennett Eq. 3.11b)"),
    (r't_\parallel=\frac{2n_i\cos\theta_i}{n_t\cos\theta_i+n_i\cos\theta_t}',
     "p-polarisation transmission coefficient  (Bennett Eq. 3.12b)"),
    (r'r=\frac{n_i-n_t}{n_i+n_t}\quad t=\frac{2n_i}{n_i+n_t}',
     "Normal incidence — MEMORISE  (theta-i = 0)"),
    (r'r_\text{air\to glass}=\frac{1-1.5}{1+1.5}=-0.2\quad R=0.04',
     "Air to glass n=1.5: 4% reflected — negative sign = pi phase shift"),
    (None, "Negative r means pi phase shift on reflection (n increases)"),
    (None, "No phase shift when going from denser to rarer medium"),
    (None, "Phase shifts critical for thin film interference — Week 6"),
    (r'\text{Example at }\theta_i=40°:\;r_s=-0.278,\;r_p=+0.119',
     "Air to glass 40 degrees: s reflects more than p"),
],
'FresnelFullExample': [
    (r'n_i=1.0,\;n_t=1.5,\;\theta_i=40°',
     "Given: air to glass, angle 40 degrees"),
    (r'\sin\theta_t=\frac{1.0}{1.5}\sin40°=0.4285\;\Rightarrow\;\theta_t=25.37°',
     "Snell's law — refracted angle"),
    (r'r_\perp=\frac{0.766-1.5\times0.904}{0.766+1.5\times0.904}=-0.278\;\Rightarrow\;R_s=0.0772',
     "s-pol: 7.7% reflected"),
    (r'r_\parallel=\frac{1.5\times0.766-0.904}{1.5\times0.766+0.904}=+0.119\;\Rightarrow\;R_p=0.0143',
     "p-pol: 1.4% reflected"),
    (r'T_s=1-0.077=0.923\quad T_p=1-0.014=0.986\quad R+T=1\;\checkmark',
     "Energy conservation verified for both polarisations"),
    (None, "p-pol near Brewster's angle: much less reflection than s-pol"),
    (None, "This difference is exploited in polarising beam splitters"),
],
'ReflectivityTransmissivity': [
    (r'R=|r|^2',
     "Reflectivity = modulus squared of amplitude coefficient"),
    (r'T=\frac{n_t\cos\theta_t}{n_i\cos\theta_i}|t|^2',
     "Transmissivity — NOT simply |t|^2, includes beam geometry"),
    (r'R+T=1',
     "Energy conservation — ALWAYS verify this in exam"),
    (None, "T = |t|² is a common and fatal exam error — include the ratio"),
    (None, "Normal incidence air/glass: R=0.04, T=0.96, sum=1.00 — check"),
    (None, "Camera lens with 10 surfaces, no AR coating: only 66% transmitted"),
],
'BrewsterTIR': [
    (r'\tan\theta_B=n_t/n_i',
     "Brewster's angle — r-p = 0, reflected beam purely s-polarised"),
    (r'\sin\theta_c=n_t/n_i\quad(n_i>n_t)',
     "Critical angle for total internal reflection"),
    (r'\theta_B(\text{air/glass})=\arctan(1.5)=56.3°',
     "Brewster angle for n=1.5 glass"),
    (r'\theta_c(\text{glass/air})=\arcsin(1/1.5)=41.8°',
     "Critical angle for n=1.5 glass to air"),
    (None, "At Brewster: reflected + refracted beams perpendicular"),
    (None, "Laser Brewster windows: p-pol passes with zero reflection loss"),
    (None, "TIR: R = 1.000 exactly — used in optical fibres and prisms"),
    (None, "Diamond: theta-c = 24.4 degrees — total reflection makes it sparkle"),
],
'MalusLaw': [
    (r'I=I_0\cos^2\theta',
     "Malus's Law  (Bennett Eq. 6.6)"),
    (None, "theta = 0: full transmission | theta = 90: complete extinction"),
    (None, "theta = 45: exactly half the intensity transmitted"),
    (None, "Three crossed polarisers: 0, 45, 90 degrees"),
    (r'I_1=I_0/2\quad I_2=I_0/4\quad I_3=I_0/8',
     "Three polariser sequence — inserting middle one allows some light through"),
    (None, "Without middle polariser: zero output (0 and 90 are crossed)"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 3 — GEOMETRIC OPTICS
# ═══════════════════════════════════════════════════════════════════════════════
'Week3TitleCard': [
    (None, "Week 3: geometric optics — ray approximation to wave optics"),
    (None, "Covers every lens, mirror, microscope, telescope and camera"),
    (None, "Bennett Chapter 4 — Geometric Optics"),
    (None, "Most critical skill: sign conventions — one sign error = wrong answer"),
],
'GeometricOpticsIntro': [
    (None, "Geometric optics: wavelength << aperture size — rays in straight lines"),
    (None, "Paraxial approximation: sin theta = theta, cos theta = 1"),
    (None, "Paraxial regime: how real optical instruments are designed"),
    (r'n\cdot(\text{geometric distance})=\text{optical path length}',
     "Optical path length = n times geometric distance  (Bennett 4.2)"),
    (None, "OPL determines phase — connects to interference (Week 6)"),
],
'SignConventions': [
    (None, "Sign conventions  (Bennett Section 4.3.4) — follow rigorously"),
    (r's_o>0',
     "Object distance positive — real object on incoming side"),
    (r's_i>0\;\Rightarrow\;\text{real image}\quad s_i<0\;\Rightarrow\;\text{virtual}',
     "Image distance: positive = real, negative = virtual"),
    (r'R>0',
     "Radius positive if centre of curvature on transmitted side"),
    (r'm=-s_i/s_o',
     "Magnification — negative means inverted image"),
    (None, "m < 0: inverted | m > 0: upright | |m| > 1: enlarged"),
    (None, "Mirror convention: positive toward incoming light (reversed)"),
    (None, "ALWAYS draw a ray diagram first — it predicts sign of answer"),
],
'SphericalSurface': [
    (r'\frac{n_i}{s_o}+\frac{n_t}{s_i}=\frac{n_t-n_i}{R}',
     "Refraction at spherical surface  (Bennett Eq. 4.18)"),
    (r'\frac{n_i}{s_o}+\frac{n_t}{s_i}=0\;\Rightarrow\;s_i=-\frac{n_t}{n_i}s_o',
     "Flat surface (R->inf): apparent depth = n_t/n_i times real depth"),
    (None, "Pool appears 75% as deep as it really is when viewed from air"),
    (r'\text{Example: }n_i=1.0,\;n_t=1.5,\;R=10\,\mathrm{cm},\;s_o=30\,\mathrm{cm}',
     "Convex glass surface — find image distance"),
],
'ThinLensScene': [
    (r'\frac{1}{s_o}+\frac{1}{s_i}=\frac{1}{f}',
     "Thin lens equation  (Bennett Eq. 4.26)"),
    (r'm=-\frac{s_i}{s_o}',
     "Lateral magnification"),
    (r'P=\frac{1}{f}\;[\mathrm{D}]',
     "Dioptric power — optometrists use dioptres"),
    (r'\frac{1}{f}=(n_l-n_m)\!\left(\frac{1}{R_1}-\frac{1}{R_2}\right)',
     "Lensmaker's equation  (Bennett Eq. 4.30)"),
    (None, "Contact lenses: P_eff = P1 + P2 when d = 0"),
    (r's_o=60\,\text{cm},\;f=20\,\text{cm}\;\Rightarrow\;s_i=30\,\text{cm},\;m=-0.5',
     "Example 1: object at 3f gives image at 1.5f, half size"),
    (r's_o=30\,\text{cm},\;f=20\,\text{cm}\;\Rightarrow\;s_i=60\,\text{cm},\;m=-2',
     "Example 2: object at 1.5f gives image at 3f, double size"),
    (r's_o=10\,\text{cm},\;f=20\,\text{cm}\;\Rightarrow\;s_i=-20\,\text{cm},\;m=+2',
     "Example 3: inside focal length — virtual upright enlarged image"),
    (None, "Virtual image: cannot be projected on screen, only seen through lens"),
    (r'R_1=+20,\;R_2=-20\,\text{cm},\;n_l=1.5\;\Rightarrow\;f=20\,\text{cm}',
     "Biconvex lens lensmaker's equation worked out"),
    (None, "Principal ray 1: parallel to axis, bends through far focal point"),
],
'MirrorScene': [
    (r'\frac{1}{s_o}+\frac{1}{s_i}=\frac{2}{R}=\frac{1}{f_m}\quad f_m=\frac{R}{2}',
     "Mirror equation — same form as thin lens  (Bennett 4.3.2)"),
    (r's_o=60,\;f_m=20\,\text{cm}\;\Rightarrow\;s_i=30\,\text{cm},\;m=-0.5',
     "Concave mirror: real inverted half-size image"),
    (r's_o=10,\;f_m=20\,\text{cm}\;\Rightarrow\;s_i=-20\,\text{cm},\;m=+2',
     "Inside focal length: virtual upright magnified — shaving mirror"),
    (None, "Concave: converging, used in telescopes — no chromatic aberration"),
    (None, "Convex: diverging, negative f, wide field — rear-view mirrors"),
],
'LensCombinations': [
    (None, "Two lenses: image of first = object of second  (Bennett 4.4)"),
    (r's_{o2}=d-s_{i1}',
     "Second object distance = separation minus first image distance"),
    (r'\frac{1}{f_\mathrm{eff}}=\frac{1}{f_1}+\frac{1}{f_2}-\frac{d}{f_1 f_2}',
     "Effective focal length of two-lens system"),
    (r'P_\mathrm{eff}=P_1+P_2\;\text{(contact, }d=0)',
     "Contact lenses: powers add directly"),
    (None, "Total magnification = m1 times m2 — magnifications multiply"),
    (r'\frac{1}{f_1}=\frac{1}{f_2}=f,\;d=f\;\Rightarrow\;f_\mathrm{eff}=f',
     "4-f relay system: two equal lenses, separation f, focal length unchanged"),
],
'OpticalInstruments': [
    (r'M_\mathrm{mag}=\frac{25\,\text{cm}}{f}',
     "Magnifying glass: angular magnification  (Bennett 4.5)"),
    (r'M_\mathrm{micro}=-\frac{L}{f_\mathrm{ob}}\cdot\frac{25\,\text{cm}}{f_e}',
     "Compound microscope magnification  (Bennett Eq. 4.42)"),
    (r'M_\mathrm{tel}=-\frac{f_\mathrm{ob}}{f_e}',
     "Astronomical telescope magnification"),
    (None, "Microscope: f_ob=4mm, f_e=25mm, L=160mm -> M = -40"),
    (None, "Telescope: f_ob=100cm, f_e=2cm -> M = -50"),
    (None, "Eye: 22 mm focal length, retina 22 mm from lens system"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 4 — MATRIX OPTICS + SUPERPOSITION + POLARISATION
# ═══════════════════════════════════════════════════════════════════════════════
'Week4TitleCard': [
    (None, "Week 4: three topics — matrix optics, superposition, polarisation"),
    (None, "Matrix optics: any optical system as a 2x2 matrix  (Bennett 5.5)"),
    (None, "Superposition: standing waves and beating  (Bennett 7.1-7.2)"),
    (None, "Polarisation introduction  (Bennett 6.1-6.4)"),
    (None, "Matrix methods used in Jones calculus — Week 5"),
],
'MatrixOpticsIntro': [
    (None, "Matrix methods in paraxial optics  (Bennett Section 5.5)"),
    (r'\begin{pmatrix}y_2\\\theta_2\end{pmatrix}=\mathbf{M}\begin{pmatrix}y_1\\\theta_1\end{pmatrix}',
     "Ray column vector: height y and angle theta"),
    (None, "Each element is a 2x2 matrix — multiply to cascade elements"),
    (r'\det(\mathbf{M})=AD-BC=1',
     "System matrix determinant always equals 1 — use as check"),
],
'MatrixEquations': [
    (r'\mathbf{M}_T=\begin{pmatrix}1&d\\0&1\end{pmatrix}',
     "Translation matrix: height changes by d*theta  (Bennett Eq. 5.35)"),
    (r'\mathbf{M}_L=\begin{pmatrix}1&0\\-1/f&1\end{pmatrix}',
     "Thin lens matrix  (Bennett Eq. 5.36)"),
    (r'\mathbf{M}_M=\begin{pmatrix}1&0\\-2/R&1\end{pmatrix}',
     "Mirror matrix — identical to lens with f = R/2"),
    (r'\mathbf{M}_\mathrm{sys}=\mathbf{M}_N\cdots\mathbf{M}_2\mathbf{M}_1',
     "System matrix: first element on RIGHT  (Bennett Eq. 5.38)"),
    (None, "Order matters — matrix multiplication is not commutative"),
],
'SystemMatrixCardinalPoints': [
    (r'f_\mathrm{eff}=-1/C',
     "Effective focal length from system matrix element C"),
    (r'\mathrm{BFD}=(D-1)/C\quad\mathrm{FFD}=-A/C',
     "Back and front focal distances"),
    (None, "C = 0: afocal system (telescope/beam expander) — parallel in, parallel out"),
    (r'AD-BC=1\;\checkmark',
     "Verify determinant = 1 after every matrix multiplication"),
    (None, "All imaging properties encoded in just 3 quantities: 2 principal planes + f"),
],
'MatrixExample': [
    (r'd=f_1+f_2\;\Rightarrow\;C=0',
     "Beam expander: separation = sum of focal lengths — afocal"),
    (r'A=-f_2/f_1',
     "A element gives beam magnification factor"),
    (None, "Input: height y, zero angle — output: -f2/f1 * y, zero angle"),
    (None, "Beam expanded by f2/f1, sign flip = beam is inverted"),
    (None, "Galilean: diverging f1, converging f2 — no intermediate focus"),
],
'StandingWaves': [
    (r'\Psi_1+\Psi_2=2A\sin(kx)\cos(\omega t)',
     "Standing wave = two oppositely travelling waves  (Bennett 7.1)"),
    (r'k x_\mathrm{node}=m\pi\;\Rightarrow\;x=m\lambda/2',
     "NODES: always zero, spaced lambda/2 apart"),
    (r'k x_\mathrm{antinode}=(m+\tfrac{1}{2})\pi',
     "ANTINODES: maximum amplitude 2A"),
    (r'2L=N\lambda\;\Rightarrow\;\lambda_N=2L/N',
     "Laser cavity: only N half-wavelengths allowed between mirrors"),
    (r'\Delta f=c/2L',
     "Mode spacing — 500 MHz for 30 cm cavity"),
    (None, "Guitar string: nodes at both fixed ends — same condition"),
],
'Beating': [
    (r'A\cos\omega_1 t+A\cos\omega_2 t=2A\cos\!\left(\frac{\omega_1-\omega_2}{2}t\right)\cos\!\left(\frac{\omega_1+\omega_2}{2}t\right)',
     "Beating: sum-to-product identity  (Bennett Section 7.2)"),
    (r'f_\mathrm{beat}=|f_1-f_2|',
     "Beat frequency = absolute difference of two frequencies"),
    (None, "Fast carrier at average frequency, slow envelope at beat frequency"),
    (None, "Tuning: adjust until beats disappear — frequencies now equal"),
    (None, "Optical heterodyne: beat signal at radio frequency — easily processed"),
    (None, "LIDAR, coherent comms and spectroscopy all use optical beating"),
],
'PolarizationBasics': [
    (r'\mathbf{E}(z,t)=E_x\hat{x}+E_y e^{i\Delta\phi}\hat{y}',
     "E field has x and y components with relative phase Delta-phi"),
    (r'\Delta\phi=0\;\text{or}\;\pi',
     "LINEAR: E oscillates along fixed line"),
    (r'|E_x|=|E_y|,\;\Delta\phi=\pm\pi/2',
     "CIRCULAR: E-tip traces a circle"),
    (None, "ELLIPTICAL: general case — any amplitudes and any phase difference"),
    (None, "Natural light: polarisation randomises every ~10 ns — unpolarised"),
    (None, "Unpolarised through polariser: I0/2 — all orientations average"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 5 — JONES FORMALISM
# ═══════════════════════════════════════════════════════════════════════════════
'Week5TitleCard': [
    (None, "Week 5: Jones vector and Jones matrix calculus  (Bennett Ch. 6)"),
    (None, "Jones vector: 2-component complex column vector for any polarisation"),
    (None, "Jones matrix: 2x2 complex matrix for any polarisation element"),
    (None, "Bennett Table 6.1 — memorise all matrices"),
],
'PolarisationStatesScene': [
    (r'\tilde{\mathbf{E}}=\begin{pmatrix}E_{0x}\\E_{0y}e^{i\Delta\phi}\end{pmatrix}',
     "General polarisation state  (Bennett Eq. 6.13)"),
    (r'\Delta\phi=0:\;\text{linear}\quad\Delta\phi=\pi/2:\;\text{circular}\quad\text{else: elliptical}',
     "Phase difference determines polarisation state"),
    (None, "LCP: Delta-phi = +pi/2, field rotates counterclockwise from receiver"),
    (None, "RCP: Delta-phi = -pi/2"),
    (r'I=\varepsilon_0 v|E_{0x}|^2/2+\varepsilon_0 v|E_{0y}|^2/2',
     "Irradiance = sum of x and y contributions  (Bennett Eq. 6.16)"),
    (None, "Unpolarised through polariser: I0/2 — average of all cos²theta"),
],
'BirefringenceWavePlates': [
    (None, "Birefringent crystal: different n for different polarisation directions"),
    (r'n_e(\mathrm{calcite})=1.4849\quad n_o(\mathrm{calcite})=1.6584',
     "Calcite at 589 nm — extraordinary vs ordinary index  (Bennett 6.3)"),
    (r'\Delta\phi=\frac{2\pi d}{\lambda_0}|n_o-n_e|',
     "Phase shift from wave plate of thickness d  (Bennett Eq. 6.8)"),
    (r'd_\mathrm{QWP}=\frac{\lambda_0}{4|n_e-n_o|}',
     "Quarter-wave plate — Delta-phi = pi/2  (Bennett Eq. 6.10)"),
    (r'd_\mathrm{HWP}=\frac{\lambda_0}{2|n_e-n_o|}',
     "Half-wave plate — Delta-phi = pi  (Bennett Eq. 6.11)"),
    (None, "QWP converts +/-45 deg linear to circular — and back"),
    (None, "HWP rotates linear polarisation by 2*alpha  (alpha = fast-axis angle)"),
    (None, "Bennett Example 6.4: LCP through QWP fast-H gives -45 deg linear"),
],
'JonesFormalism': [
    (None, "Jones vectors introduced by R. Clark Jones, 1941  (Bennett 6.5)"),
    (r'\tilde{E}=\begin{pmatrix}E_{0x}\\E_{0y}\end{pmatrix}',
     "Jones vector — complex amplitude column vector"),
    (None, "Common factor exp(i(kz-omega t)) is implicit — not written"),
    (r'\begin{pmatrix}1\\0\end{pmatrix}\;\begin{pmatrix}0\\1\end{pmatrix}\;\frac{1}{\sqrt{2}}\begin{pmatrix}1\\1\end{pmatrix}\;\frac{1}{\sqrt{2}}\begin{pmatrix}1\\-1\end{pmatrix}',
     "H-linear, V-linear, +45, -45 degree Jones vectors"),
    (r'\frac{1}{\sqrt{2}}\begin{pmatrix}1\\i\end{pmatrix}\;\text{LCP}\qquad\frac{1}{\sqrt{2}}\begin{pmatrix}1\\-i\end{pmatrix}\;\text{RCP}',
     "Left and right circular Jones vectors  (Bennett Table 6.1)"),
    (r'I=|\tilde{E}|^2=|E_{0x}|^2+|E_{0y}|^2',
     "Intensity from Jones vector: modulus squared"),
    (None, "LCP and RCP form an alternative basis — equally valid to H,V"),
    (None, "Specifying Jones vector = fully specifying polarisation state"),
],
'JonesMatrices': [
    (r'\tilde{E}_t=\mathbf{M}\tilde{E}_i',
     "Jones matrix M transforms input to output  (Bennett Eq. 6.22)"),
    (r'\mathbf{M}_\mathrm{total}=\mathbf{M}_N\cdots\mathbf{M}_2\mathbf{M}_1',
     "Cascade: first element on RIGHT  (Bennett Eq. 6.23)"),
    (r'\mathbf{M}_{H-pol}=\begin{pmatrix}1&0\\0&0\end{pmatrix}\quad\mathbf{M}_{V-pol}=\begin{pmatrix}0&0\\0&1\end{pmatrix}',
     "Horizontal and vertical polarisers  (Bennett Table 6.1)"),
    (r'\mathbf{M}_\mathrm{QWP-H}=\begin{pmatrix}1&0\\0&i\end{pmatrix}\quad\mathbf{M}_\mathrm{QWP-V}=\begin{pmatrix}1&0\\0&-i\end{pmatrix}',
     "QWP with fast axis horizontal and vertical  (Bennett Table 6.1)"),
    (r'\mathbf{M}_\mathrm{HWP-H}=\begin{pmatrix}1&0\\0&-1\end{pmatrix}',
     "HWP with fast axis horizontal"),
    (r'\mathbf{R}(\alpha)=\begin{pmatrix}\cos\alpha&-\sin\alpha\\\sin\alpha&\cos\alpha\end{pmatrix}',
     "Rotation matrix  (Bennett Example 6.5)  — rotated matrix: R M R^{-1}"),
    (r'\begin{pmatrix}0&0\\0&1\end{pmatrix}\frac{1}{\sqrt{2}}\begin{pmatrix}1\\1\end{pmatrix}=\frac{1}{\sqrt{2}}\begin{pmatrix}0\\1\end{pmatrix}',
     "Bennett Example 6.6a: +45 through V-polariser -> V-linear, I/2"),
    (r'\begin{pmatrix}1&0\\0&i\end{pmatrix}\frac{1}{\sqrt{2}}\begin{pmatrix}1\\1\end{pmatrix}=\frac{1}{\sqrt{2}}\begin{pmatrix}1\\i\end{pmatrix}',
     "Bennett Example 6.6b: +45 through QWP-H -> LCP, no intensity loss"),
    (r'\mathbf{M}^\prime=\mathbf{R}(\alpha)\mathbf{M}\mathbf{R}(-\alpha)',
     "Rotated element matrix  (Bennett Eq. 6.24)"),
    (None, "Example 6.7: HWP + QWP + polariser — multiply 3 matrices"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 6 — INTERFERENCE
# ═══════════════════════════════════════════════════════════════════════════════
'Week6TitleCard': [
    (None, "Week 6: interference — the wave nature of light made visible"),
    (None, "Superposition: fields add, intensity can be 4x or 0"),
    (None, "Bennett Chapter 7 Sections 7.3 through 7.8 and 7.12"),
    (None, "Applications: AR coatings, LIGO, OCT, spectroscopy"),
],
'InterferenceIntroScene': [
    (None, "Interference: superposition of coherent waves gives non-trivial intensity"),
    (r'I=I_1+I_2+2\sqrt{I_1 I_2}\cos\delta',
     "General two-beam interference formula  (Bennett Eq. 7.14)"),
    (None, "Constructive: delta = 2m*pi -> I_max = (sqrt(I1)+sqrt(I2))^2"),
    (None, "Destructive: delta = (2m+1)*pi -> I_min = (sqrt(I1)-sqrt(I2))^2"),
    (None, "Equal beams I1=I2=I0: I ranges from 0 to 4*I0"),
    (None, "Energy conserved — bright and dark fringes average to I1+I2"),
],
'TwoBeamInterference': [
    (r'\tilde{E}_\mathrm{tot}=E_1 e^{i\phi_1}+E_2 e^{i\phi_2}',
     "Total field = sum of two complex amplitudes"),
    (r'I=|\tilde{E}_\mathrm{tot}|^2=I_1+I_2+2\sqrt{I_1 I_2}\cos\delta\quad\delta=\phi_2-\phi_1',
     "Expand modulus squared — interference term appears"),
    (r'\delta=\frac{2\pi}{\lambda}\cdot\text{OPD}+\Delta\phi_\mathrm{refl}',
     "Phase difference from optical path difference + reflection shifts"),
    (None, "Two sources of phase difference: geometry and reflection"),
    (None, "Reflection shift: +pi when n increases, 0 when n decreases"),
],
'YoungDoubleSlit': [
    (r'd\sin\theta_m=m\lambda\;\Rightarrow\;\text{bright fringes}',
     "Young's bright fringe condition  (Bennett Eq. 7.18)"),
    (r'\Delta y=\frac{\lambda L}{d}',
     "Fringe spacing on screen at distance L  (Bennett Eq. 7.19)"),
    (r'I=4I_0\cos^2\!\left(\frac{\pi d y}{\lambda L}\right)',
     "Intensity pattern — cosine squared"),
    (None, "Example: d=0.1mm, L=1.5m, lambda=589nm -> Delta-y = 8.84mm"),
    (r'\text{5th bright fringe: }y_5=5\times8.84=44.2\,\text{mm}',
     "Fifth fringe position above centre"),
    (None, "Young 1801: first conclusive proof light is a wave"),
    (None, "Envelope modulated by single-slit diffraction function — Week 7"),
],
'ThinFilmInterference': [
    (r'\delta=\frac{4\pi n_f t\cos\theta_t}{\lambda_0}+\Delta\phi_\mathrm{refl}',
     "Phase difference for thin film  (Bennett Eq. 7.26)"),
    (None, "Step 1: for each reflection, does n increase? Yes -> +pi shift"),
    (None, "Step 2: net phase shift = beam2 shifts minus beam1 shifts"),
    (r'\delta=2m\pi\;\text{constructive}\quad\delta=(2m+1)\pi\;\text{destructive}',
     "Constructive and destructive reflection conditions"),
    (None, "AR coating: MgF2 (n=1.38) on glass (n=1.52)"),
    (None, "Both reflections: n increases each time -> both +pi -> net shift = 0"),
    (r'2n_f t=\lambda/2\;\Rightarrow\;t=\frac{\lambda_0}{4n_f}=99.6\,\text{nm}',
     "AR condition: destructive -> t = lambda0/(4*n_f)"),
    (None, "Soap bubble colours: varying thickness gives different resonant lambda"),
    (None, "White light: all wavelengths present, different colours cancel at each t"),
    (None, "Exam: always track both reflection phase shifts carefully"),
],
'FringeVisibility': [
    (r'V=\frac{I_\mathrm{max}-I_\mathrm{min}}{I_\mathrm{max}+I_\mathrm{min}}',
     "Fringe visibility  (Bennett Eq. 7.30)"),
    (r'V=\frac{2\sqrt{I_1 I_2}}{I_1+I_2}',
     "Visibility maximised when I1 = I2 -> V = 1"),
    (r'l_c=\frac{\lambda^2}{\Delta\lambda}=\frac{c}{\Delta\nu}',
     "Coherence length — OPD must be less than l_c for fringes"),
    (None, "White light: l_c ~ 1 micron — only nearest-order fringes visible"),
    (None, "Sodium lamp Delta-lambda~0.001nm: l_c ~ 0.35 m"),
    (None, "He-Ne laser Delta-nu~1MHz: l_c ~ 300 m"),
],
'MichelsonScene': [
    (r'\mathrm{OPD}=2\Delta L\;\Rightarrow\;\delta=\frac{4\pi\Delta L}{\lambda}',
     "Michelson: mirror displacement Delta-L gives OPD = 2*Delta-L"),
    (r'N=\frac{2\Delta L}{\lambda}\;\Rightarrow\;\lambda=\frac{2\Delta L}{N}',
     "Count N fringes as mirror moves Delta-L -> measure wavelength"),
    (r'\mathrm{RP}=\frac{2L}{\lambda}',
     "Resolving power = 2L/lambda — longer path, sharper resolution"),
    (None, "Michelson 1881: searched for aether — null result led to relativity"),
    (None, "LIGO: 4 km arms, FP cavities give 1600 km effective path"),
    (r'\Delta L_\mathrm{LIGO}=10^{-18}\,\text{m}=10^{-4}\times d_\text{proton}',
     "LIGO sensitivity: 0.0001 proton diameters"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 7 — DIFFRACTION
# ═══════════════════════════════════════════════════════════════════════════════
'Week7TitleCard': [
    (None, "Week 7: diffraction — wave optics when aperture ~ wavelength"),
    (None, "Huygens: every point on wavefront = secondary spherical source"),
    (None, "Fraunhofer pattern = Fourier transform of aperture  (Bennett Ch. 8)"),
    (None, "Larger aperture -> narrower pattern — optical uncertainty principle"),
],
'HuygensPrinciple': [
    (None, "Huygens 1678: each wavefront point emits a secondary wavelet"),
    (None, "Bennett Ch. 8: diffraction is interference done correctly"),
    (None, "Young: 2 discrete sources — Diffraction: continuous aperture"),
    (r'L\gg\frac{a^2}{2\lambda}\;\Rightarrow\;\text{Fraunhofer (far field)}',
     "Fraunhofer condition: screen in far field of aperture"),
    (None, "a=0.1mm, lambda=500nm, L=2m: far field at L >> 0.02m — yes"),
],
'SingleSlitDiffraction': [
    (r'I=I_0\left(\frac{\sin\beta}{\beta}\right)^2\quad\beta=\frac{\pi b\sin\theta}{\lambda}',
     "Single-slit Fraunhofer pattern — sinc squared  (Bennett 8.3.1)"),
    (r'b\sin\theta=m\lambda\;\Rightarrow\;\text{dark minima}',
     "Minima condition — m nonzero integer"),
    (r'\theta_\mathrm{half}=\arcsin(\lambda/b)\approx\lambda/b',
     "Half-width of central maximum in radians"),
    (None, "Narrower slit -> wider diffraction pattern — inverse relationship"),
    (None, "Secondary maxima at ~4.7% and ~1.7% of central maximum"),
    (r'b=0.2\,\text{mm},\;\lambda=632.8\,\text{nm},\;L=2\,\text{m}:',
     "Worked example — He-Ne laser and 0.2 mm slit"),
    (r'y_1=L\sin\theta_1=L\lambda/b=6.33\,\text{mm}',
     "First dark fringe at 6.33 mm — central lobe width 12.7 mm"),
],
'CircularApertureRayleigh': [
    (r'I=I_0\left(\frac{2J_1(x)}{x}\right)^2\quad x=\frac{\pi D r}{\lambda z}',
     "Circular aperture — Airy disk with Bessel function J_1"),
    (r'\sin\theta_1=\frac{1.22\lambda}{D}',
     "First dark ring — factor 1.22 from first zero of J_1  (Bennett 8.3.3)"),
    (r'\theta_\mathrm{min}=1.22\lambda/D',
     "Rayleigh criterion — minimum resolvable angular separation"),
    (r'\theta_\mathrm{eye}=1.22\times550\,\text{nm}/3\,\text{mm}=2.2\times10^{-4}\,\text{rad}',
     "Human eye: ~46 arcseconds resolution at 3 mm pupil"),
    (r'\theta_\mathrm{HST}=1.22\times550\,\text{nm}/2.4\,\text{m}=2.8\times10^{-7}\,\text{rad}',
     "Hubble: 0.058 arcseconds — 800x sharper than eye"),
    (None, "Better resolution: increase D or decrease lambda"),
    (None, "VLBI: Earth diameter baseline — microarcsecond resolution"),
],
'DiffractionGrating': [
    (r'd\sin\theta_m=m\lambda',
     "Grating equation for normal incidence  (Bennett Eq. 8.38)"),
    (r'\mathrm{RP}=\frac{\lambda}{\delta\lambda}=Nm',
     "Resolving power = N slits times order m  (Bennett Eq. 8.42)"),
    (r'\Delta\lambda_\mathrm{FSR}=\lambda_\mathrm{min}/m',
     "Free spectral range — unambiguous wavelength interval"),
    (None, "600 gr/mm grating, 5 cm: N=30000, RP=30000 in first order"),
    (r'\delta\lambda_\mathrm{min}=589/30000=0.020\,\text{nm}',
     "Resolves wavelengths 0.020 nm apart"),
    (None, "Sodium D lines: 0.6 nm separation — easily resolved"),
    (r'd(\sin\theta_m-\sin\theta_i)=m\lambda',
     "Oblique incidence grating equation"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# WEEK 8 — FABRY-PEROT
# ═══════════════════════════════════════════════════════════════════════════════
'Week8TitleCard': [
    (None, "Week 8: Fabry-Perot interferometer  (Bennett 7.10-7.12)"),
    (None, "Multiple reflections between two mirrors — infinite geometric series"),
    (None, "Airy function: sharp transmission peaks at resonance"),
    (None, "Resolving power far exceeds diffraction gratings"),
],
'MultiBeamIntro': [
    (None, "Two-beam Michelson: sinusoidal fringes, limited resolving power"),
    (r'\tilde{T}=\frac{t^2}{1-r^2 e^{i\delta}}\quad\delta=\frac{4\pi nd\cos\theta}{\lambda_0}',
     "Fabry-Perot: geometric series sums to this complex transmission"),
    (None, "t^2 = 1-r^2 (energy conservation at each mirror)"),
    (None, "At resonance: all partial beams in phase — 100% transmission"),
    (None, "Off resonance: beams partially cancel — very low transmission"),
],
'AiryFunction': [
    (r'I_t=\frac{I_0}{1+F\sin^2(\delta/2)}\quad F=\frac{4R}{(1-R)^2}',
     "The Airy function  (Bennett Eq. 7.89)"),
    (None, "F = coefficient of finesse — NOT the same as script-F finesse"),
    (r'\delta=2N\pi:\;I_t=I_0',
     "AT RESONANCE: complete transmission regardless of R"),
    (r'R=0.9:\;F=360\;\Rightarrow\;I_t^\mathrm{off}=I_0/361<0.3\%',
     "Off resonance with R=0.9: less than 0.3% transmitted"),
    (None, "High R: F large -> peaks become extremely sharp"),
],
'FinesseResolving': [
    (r'\mathcal{F}=\frac{\pi\sqrt{R}}{1-R}=\frac{\pi\sqrt{F}}{2}',
     "FINESSE script-F  (Bennett Section 7.10) — NOT F"),
    (r'N=\frac{2nd\cos\theta}{\lambda_0}',
     "Order number at resonance"),
    (r'\mathrm{RP}=N\mathcal{F}',
     "Resolving power = order number times finesse"),
    (r'\Delta\lambda_\mathrm{FSR}=\frac{\lambda_0^2}{2nd}\quad\Delta\nu_\mathrm{FSR}=\frac{c}{2nd}',
     "Free spectral range in wavelength and frequency"),
    (r'R=0.9:\;\mathcal{F}=29.8\qquad R=0.99:\;\mathcal{F}=312',
     "Finesse values for typical reflectivities"),
    (None, "EXAM WARNING: never put F where script-F is needed — off by factor ~15"),
],
'FabryPerotExample': [
    (r'R=0.90,\;\lambda_0=656.2\,\text{nm},\;\Delta\lambda=0.18\,\text{nm}',
     "H and D alpha lines — Bennett Example 7.11"),
    (r'F=\frac{4\times0.9}{0.01}=360\quad\mathcal{F}=\frac{\pi\sqrt{360}}{2}=29.8',
     "Step 1: coefficient of finesse and finesse"),
    (r'd=\frac{\lambda_0^2}{2\Delta\lambda_\mathrm{FSR}}=\frac{656.2^2}{2\times0.5}=0.431\,\text{mm}',
     "Step 2: choose FSR=0.5nm, find mirror spacing"),
    (r'N=\frac{2d}{\lambda_0}=\frac{2\times0.431\,\text{mm}}{656.2\,\text{nm}}=1313',
     "Step 3: order number"),
    (r'\mathrm{RP}=N\mathcal{F}=1313\times29.8=39100',
     "Step 4: resolving power"),
    (r'\delta\lambda_\mathrm{min}=\frac{656.2}{39100}=0.0168\,\text{nm}\ll0.18\,\text{nm}\;\checkmark',
     "Step 5: minimum resolvable — much smaller than 0.18 nm separation"),
    (None, "H and D alpha lines clearly resolved with 0.43 mm cavity"),
    (None, "Compare: 30000-slit grating RP=30000 — FP wins"),
],
'CoherenceLength': [
    (r'l_c=\frac{\lambda^2}{\Delta\lambda}=\frac{c}{\Delta\nu}',
     "Coherence length  (Bennett Section 7.12)"),
    (r'\tau_c=l_c/c=1/\Delta\nu',
     "Coherence time"),
    (r'\text{White light: }l_c\approx1\,\mu\text{m}\quad\text{Na lamp: }l_c\approx0.35\,\text{m}',
     "Coherence lengths for common sources"),
    (r'\text{He-Ne: }l_c\approx300\,\text{m}\quad\text{LIGO laser: }l_c\approx300\,000\,\text{km}',
     "Laser coherence lengths — LIGO needs extraordinary stability"),
    (None, "FP cavity: OPD = 2nd must be less than l_c for fringes to form"),
    (None, "White light FP: only works for very small d — impractical"),
    (None, "Stabilised laser: delta-nu ~ mHz -> l_c ~ hundreds of thousands of km"),
],
'Week8Summary': [
    (None, "Fabry-Perot complete formula summary"),
    (r'I_t=\frac{I_0}{1+F\sin^2(\delta/2)}\quad F=\frac{4R}{(1-R)^2}\quad\delta=\frac{4\pi nd}{\lambda_0}',
     "Airy function, F coefficient and round-trip phase"),
    (r'\mathcal{F}=\frac{\pi\sqrt{R}}{1-R}\quad N=\frac{2nd}{\lambda_0}\quad\mathrm{RP}=N\mathcal{F}',
     "Finesse, order number and resolving power"),
    (r'\Delta\lambda_\mathrm{FSR}=\frac{\lambda_0^2}{2nd}=\frac{\lambda_0}{N}\quad\Delta\nu_\mathrm{FSR}=\frac{c}{2nd}',
     "Free spectral range in both lambda and frequency"),
    (None, "OPD = 2nd must be less than coherence length"),
    (None, "R=0.9: F=360, finesse=29.8 | R=0.99: F=39600, finesse=312"),
    (None, "EXAM: F (coefficient) vs script-F (finesse) — very different numbers"),
    (None, "Most common error: substituting F in place of script-F"),
],

# ═══════════════════════════════════════════════════════════════════════════════
# FORMULA SHEET
# ═══════════════════════════════════════════════════════════════════════════════
'FormulaSheetTitleCard': [
    (None, "Complete formula reference for 31OPT Optics"),
    (None, "Know when to use each formula — not just the algebra"),
    (None, "Approach: formula -> substitute with units -> check reasonableness"),
],
'MidtermPrepScene': [
    (None, "Midterm covers Weeks 1-3: waves, Maxwell, Fresnel, geometric optics"),
    (r'\frac{\partial^2\Psi}{\partial x^2}=\frac{1}{v^2}\frac{\partial^2\Psi}{\partial t^2}\quad v=f\lambda=\frac{\omega}{k}',
     "Week 1: wave equation and harmonic wave relations"),
    (r'n_i\sin\theta_i=n_t\sin\theta_t\quad r_\perp,r_\parallel,R+T=1',
     "Week 2: Snell's law, Fresnel coefficients, energy conservation"),
    (r'\frac{1}{s_o}+\frac{1}{s_i}=\frac{1}{f}\quad m=-s_i/s_o',
     "Week 3: thin lens equation and magnification"),
    (None, "Most common errors: sign conventions, T not simply |t|^2, R+T check"),
    (None, "Strategy: draw ray diagram first, then apply thin lens equation"),
],
'FinalExamPrepScene': [
    (None, "Final exam: all 8 weeks — systematic formula review"),
    (r'I=4I_0\cos^2(\pi d y/\lambda L)\quad\Delta y=\lambda L/d',
     "Week 6: Young's fringes — intensity pattern and spacing"),
    (r'I=I_0(\sin\beta/\beta)^2\quad\theta_\mathrm{min}=1.22\lambda/D\quad Nm',
     "Week 7: single slit, Rayleigh, grating resolving power"),
    (r'I_t=I_0/(1+F\sin^2\delta/2)\quad\mathrm{RP}=N\mathcal{F}\quad\Delta\nu=c/2nd',
     "Week 8: Airy function, resolving power, FSR"),
    (None, "Week 5: Jones matrices — multiply RIGHT to LEFT in order of encounter"),
    (None, "Week 4: system matrix determinant must equal 1 — always verify"),
    (None, "Exam technique: write formula, substitute with units, check answer"),
],
}

print(f"Screen content defined for {len(SC)} scenes")
total = sum(len(v) for v in SC.values())
print(f"Total screen pages: {total}")
