# week3_geometric.py — generated by gen_final.py
from manim import *
from utils import *

class Week3TitleCard_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week3TitleCard_p1.mp3", time_offset=0)
        card = make_title_card("WEEK 3", "Geometric Optics: Lenses, Mirrors and Instruments", "Bennett Ch. 4")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Week 3: geometric optics — rays, lenses, mirrors", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week3TitleCard_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week3TitleCard_p2.mp3", time_offset=0)
        card = make_title_card("WEEK 3", "Geometric Optics: Lenses, Mirrors and Instruments", "Bennett Ch. 4")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Ray optics: valid when wavelength much smaller than aperture", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week3TitleCard_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week3TitleCard_p3.mp3", time_offset=0)
        card = make_title_card("WEEK 3", "Geometric Optics: Lenses, Mirrors and Instruments", "Bennett Ch. 4")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Most critical skill: sign conventions — one error gives the wrong answer", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week3TitleCard_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week3TitleCard_p4.mp3", time_offset=0)
        card = make_title_card("WEEK 3", "Geometric Optics: Lenses, Mirrors and Instruments", "Bennett Ch. 4")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Apply thin lens, mirror equation, magnification, instruments", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class GeometricOpticsIntro_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/GeometricOpticsIntro_p1.mp3", time_offset=0)
        title = Text("Geometric Optics  (Bennett 4.1-4.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\lambda\ll a\;\Rightarrow\;\text{ray optics valid}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Geometric optics valid when wavelength much less than aperture", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class GeometricOpticsIntro_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/GeometricOpticsIntro_p2.mp3", time_offset=0)
        title = Text("Geometric Optics  (Bennett 4.1-4.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\sin\theta\approx\theta,\quad\tan\theta\approx\theta,\quad\cos\theta\approx1', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Paraxial approximation  (Bennett 4.1)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class GeometricOpticsIntro_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/GeometricOpticsIntro_p3.mp3", time_offset=0)
        title = Text("Geometric Optics  (Bennett 4.1-4.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{OPL}=n\times d_\text{geom}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Optical path length determines the accumulated phase", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class GeometricOpticsIntro_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/GeometricOpticsIntro_p4.mp3", time_offset=0)
        title = Text("Geometric Optics  (Bennett 4.1-4.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\lambda\sim a\;\Rightarrow\;\text{diffraction}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("When aperture ~ wavelength: diffraction dominates (Week 7)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class GeometricOpticsIntro_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/GeometricOpticsIntro_p5.mp3", time_offset=0)
        title = Text("Geometric Optics  (Bennett 4.1-4.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{OPL}=n\cdot d_\text{geom}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Optical path length determines phase  (Bennett 4.2)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SignConventions_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SignConventions_p1.mp3", time_offset=0)
        title = Text("Sign Conventions  (Bennett 4.3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o>0\;\text{(real object)},\quad s_i>0\;\text{(real image)},\quad f>0\;\text{(converging)}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Sign convention summary  (Bennett 4.3.4)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SignConventions_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SignConventions_p2.mp3", time_offset=0)
        title = Text("Sign Conventions  (Bennett 4.3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o>0', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Object distance: positive when real object is on the incoming side", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SignConventions_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SignConventions_p3.mp3", time_offset=0)
        title = Text("Sign Conventions  (Bennett 4.3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_i>0\Rightarrow\text{real}\quad s_i<0\Rightarrow\text{virtual}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Image distance: positive = real image, negative = virtual image", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SignConventions_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SignConventions_p4.mp3", time_offset=0)
        title = Text("Sign Conventions  (Bennett 4.3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'm=-s_i/s_o', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Lateral magnification: negative means inverted", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SignConventions_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SignConventions_p5.mp3", time_offset=0)
        title = Text("Sign Conventions  (Bennett 4.3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'R>0\;\text{if centre of curvature on transmission side}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Radius R: positive when centre is downstream", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SignConventions_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SignConventions_p6.mp3", time_offset=0)
        title = Text("Sign Conventions  (Bennett 4.3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Mirror convention: distances positive toward the incoming light direction", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class SignConventions_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SignConventions_p7.mp3", time_offset=0)
        title = Text("Sign Conventions  (Bennett 4.3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'm=-\frac{s_i}{s_o}\quad m<0\Rightarrow\text{inverted},\quad|m|>1\Rightarrow\text{enlarged}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Magnification: sign and magnitude meaning", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SignConventions_p8(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SignConventions_p8.mp3", time_offset=0)
        title = Text("Sign Conventions  (Bennett 4.3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Always draw ray diagram first — it predicts all signs before algebra", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class SphericalSurface_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SphericalSurface_p1.mp3", time_offset=0)
        title = Text("Refraction at Spherical Surface  (Bennett 4.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\frac{n_i}{s_o}+\frac{n_t}{s_i}=\frac{n_t-n_i}{R}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Refraction at a spherical surface  (Bennett Eq. 4.18)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SphericalSurface_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SphericalSurface_p2.mp3", time_offset=0)
        title = Text("Refraction at Spherical Surface  (Bennett 4.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_i=-\frac{n_t}{n_i}s_o\quad(R\to\infty)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Flat surface limit: apparent depth equals n_t over n_i times real depth", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SphericalSurface_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SphericalSurface_p3.mp3", time_offset=0)
        title = Text("Refraction at Spherical Surface  (Bennett 4.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\frac{n_i}{s_o}+\frac{n_t}{s_i}=\frac{n_t-n_i}{R}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Refraction at spherical surface  (Bennett Eq. 4.18)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SphericalSurface_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SphericalSurface_p4.mp3", time_offset=0)
        title = Text("Refraction at Spherical Surface  (Bennett 4.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'n_i=1,\;n_t=1.5,\;R=10,\;s_o=30\;\Rightarrow\;s_i=90\,\text{cm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Example: image forms 90 cm inside the glass", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SphericalSurface_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SphericalSurface_p5.mp3", time_offset=0)
        title = Text("Refraction at Spherical Surface  (Bennett 4.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'n_i=1,\;n_t=1.5,\;R=10\,\text{cm},\;s_o=30\,\text{cm}\;\Rightarrow\;s_i=90\,\text{cm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Numerical example: image 90 cm inside glass", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p1.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\frac{1}{s_o}+\frac{1}{s_i}=\frac{1}{f}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Thin lens equation  (Bennett Eq. 4.26)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p2.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'm=-s_i/s_o', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Lateral magnification", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p3.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\frac{1}{f}=(n_l-n_m)\!\left(\frac{1}{R_1}-\frac{1}{R_2}\right)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Lensmaker equation  (Bennett Eq. 4.30)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p4.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'P=\frac{1}{f}\;\text{[dioptres]},\quad P_\text{eff}=P_1+P_2\;(d=0)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Dioptric power — used in ophthalmology", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p5.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=60,\;f=20\;\Rightarrow\;s_i=30,\;m=-0.5', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Example 1: real inverted half-size image", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p6.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=30,\;f=20\;\Rightarrow\;s_i=60,\;m=-2', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Example 2: projector geometry — real inverted doubled", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p7.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=10,\;f=20\;\Rightarrow\;s_i=-20,\;m=+2', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Example 3: inside focal length — virtual upright magnified", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p8(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p8.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\frac{1}{s_i}=\frac{1}{f}-\frac{1}{s_o}=\frac{1}{20}-\frac{1}{30}=\frac{1}{60}\;\Rightarrow\;s_i=60', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Example 2: s_o=30, f=20 -> s_i=60, m=-2", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p9(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p9.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'R_1=+20,\;R_2=-20,\;n_l=1.5\;\Rightarrow\;f=20\,\text{cm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Biconvex lens lensmaker calculation", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p10(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p10.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=30\;\Rightarrow\;s_i=60,\;m=-2\quad s_o=10\;\Rightarrow\;s_i=-20,\;m=+2', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Two more examples: projector and magnifying glass", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinLensScene_p11(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinLensScene_p11.mp3", time_offset=0)
        title = Text("The Thin Lens Equation  (Bennett 4.3)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=10,\;f=20\;\Rightarrow\;\frac{1}{s_i}=\frac{1}{20}-\frac{1}{10}=-\frac{1}{20}\;\Rightarrow\;s_i=-20', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Inside focal length: virtual, upright, magnified", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MirrorScene_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MirrorScene_p1.mp3", time_offset=0)
        title = Text("Spherical Mirrors  (Bennett 4.3.2)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\frac{1}{s_o}+\frac{1}{s_i}=\frac{2}{R}=\frac{1}{f_m}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Mirror equation  (Bennett 4.3.2)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MirrorScene_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MirrorScene_p2.mp3", time_offset=0)
        title = Text("Spherical Mirrors  (Bennett 4.3.2)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=60,\;f_m=20\;\Rightarrow\;s_i=30,\;m=-0.5', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Real inverted half-size image — concave mirror", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MirrorScene_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MirrorScene_p3.mp3", time_offset=0)
        title = Text("Spherical Mirrors  (Bennett 4.3.2)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=10,\;f_m=20\;\Rightarrow\;s_i=-20,\;m=+2', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Virtual upright magnified — shaving mirror geometry", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MirrorScene_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MirrorScene_p4.mp3", time_offset=0)
        title = Text("Spherical Mirrors  (Bennett 4.3.2)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=60,\;f_m=20\;\Rightarrow\;\frac{1}{s_i}=\frac{1}{20}-\frac{1}{60}=\frac{1}{30}\;\Rightarrow\;s_i=30', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Concave mirror example: real inverted half-size", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MirrorScene_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MirrorScene_p5.mp3", time_offset=0)
        title = Text("Spherical Mirrors  (Bennett 4.3.2)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_o=10,\;f_m=20\;\Rightarrow\;\frac{1}{s_i}=\frac{1}{20}-\frac{1}{10}=-\frac{1}{20}\;\Rightarrow\;s_i=-20', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Inside focal length: virtual upright magnified — shaving mirror", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MirrorScene_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MirrorScene_p6.mp3", time_offset=0)
        title = Text("Spherical Mirrors  (Bennett 4.3.2)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Reflecting telescopes: no chromatic aberration — mirror same for all wavelengths", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class LensCombinations_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/LensCombinations_p1.mp3", time_offset=0)
        title = Text("Lens Combinations  (Bennett 4.4)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r's_{o2}=d-s_{i1}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Second object distance equals separation minus first image distance", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class LensCombinations_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/LensCombinations_p2.mp3", time_offset=0)
        title = Text("Lens Combinations  (Bennett 4.4)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\frac{1}{f_\text{eff}}=\frac{1}{f_1}+\frac{1}{f_2}-\frac{d}{f_1 f_2}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Effective focal length of two-lens combination", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class LensCombinations_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/LensCombinations_p3.mp3", time_offset=0)
        title = Text("Lens Combinations  (Bennett 4.4)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'P_\text{eff}=P_1+P_2\;(d=0)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Contact lenses: powers simply add together", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class LensCombinations_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/LensCombinations_p4.mp3", time_offset=0)
        title = Text("Lens Combinations  (Bennett 4.4)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\frac{1}{f_\text{eff}}=\frac{1}{f_1}+\frac{1}{f_2}\;(d=0),\quad P_\text{eff}=P_1+P_2', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Contact lenses: powers add directly", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class LensCombinations_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/LensCombinations_p5.mp3", time_offset=0)
        title = Text("Lens Combinations  (Bennett 4.4)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'f_1=f_2=f,\;d=f\;\Rightarrow\;1/f_\text{eff}=0', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("4-f relay system: afocal, image size unity", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class OpticalInstruments_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/OpticalInstruments_p1.mp3", time_offset=0)
        title = Text("Optical Instruments  (Bennett 4.5)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'M_\text{mag}=25\,\text{cm}/f', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Magnifying glass  (Bennett 4.5)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class OpticalInstruments_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/OpticalInstruments_p2.mp3", time_offset=0)
        title = Text("Optical Instruments  (Bennett 4.5)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'M_\text{micro}=-(L/f_\text{ob})(25\,\text{cm}/f_e)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Compound microscope  (Bennett Eq. 4.42)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class OpticalInstruments_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/OpticalInstruments_p3.mp3", time_offset=0)
        title = Text("Optical Instruments  (Bennett 4.5)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'M_\text{tel}=-f_\text{ob}/f_e', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Astronomical telescope", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class OpticalInstruments_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/OpticalInstruments_p4.mp3", time_offset=0)
        title = Text("Optical Instruments  (Bennett 4.5)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Microscope example: fob=4mm, fe=25mm, L=160mm gives M=-160", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class OpticalInstruments_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/OpticalInstruments_p5.mp3", time_offset=0)
        title = Text("Optical Instruments  (Bennett 4.5)", font_size=36, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Human eye has approximately 60 dioptres total optical power", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)
