# week2_fresnel.py — generated by gen_final.py
from manim import *
from utils import *

class Week2Intro_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week2Intro_p1.mp3", time_offset=0)
        title = Text("Week 2 Introduction", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Bridge from Maxwell equations to geometric optics", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week2Intro_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week2Intro_p2.mp3", time_offset=0)
        title = Text("Week 2 Introduction", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("The central tool: boundary conditions at every interface", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week2Intro_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week2Intro_p3.mp3", time_offset=0)
        title = Text("Week 2 Introduction", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Agenda: Snell law, Fresnel equations, Brewster angle, TIR", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week2TitleCard_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week2TitleCard_p1.mp3", time_offset=0)
        card = make_title_card("WEEK 2", "Fresnel Equations, Reflection and Refraction", "Bennett Ch. 3")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Week 2: light at an interface — determining directions and amplitudes", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week2TitleCard_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week2TitleCard_p2.mp3", time_offset=0)
        card = make_title_card("WEEK 2", "Fresnel Equations, Reflection and Refraction", "Bennett Ch. 3")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Snell law determines direction — Fresnel equations determine amplitude", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week2TitleCard_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week2TitleCard_p3.mp3", time_offset=0)
        card = make_title_card("WEEK 2", "Fresnel Equations, Reflection and Refraction", "Bennett Ch. 3")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Every lens surface, mirror coating and optical fibre depends on this", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week2TitleCard_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week2TitleCard_p4.mp3", time_offset=0)
        card = make_title_card("WEEK 2", "Fresnel Equations, Reflection and Refraction", "Bennett Ch. 3")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Bennett Chapter 3 — master the Fresnel calculation procedure completely", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class FermatPrinciple_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FermatPrinciple_p1.mp3", time_offset=0)
        title = Text("Fermat Principle  (Bennett 3.2.1)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Light takes the path of stationary optical path length  (Fermat 1662)", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FermatPrinciple_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FermatPrinciple_p2.mp3", time_offset=0)
        title = Text("Fermat Principle  (Bennett 3.2.1)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Reflection: stationary path gives angle-of-incidence equals angle-of-reflection", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FermatPrinciple_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FermatPrinciple_p3.mp3", time_offset=0)
        title = Text("Fermat Principle  (Bennett 3.2.1)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'n_i\sin\theta_i=n_t\sin\theta_t', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Refraction: stationary path gives Snell law", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FermatPrinciple_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FermatPrinciple_p4.mp3", time_offset=0)
        title = Text("Fermat Principle  (Bennett 3.2.1)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Connects to Hamilton principle in mechanics and Feynman path integral in QED", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class ReflectionRefraction_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectionRefraction_p1.mp3", time_offset=0)
        title = Text("Reflection and Snell Law  (Bennett 3.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\theta_i=\theta_r', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Law of reflection — angle in equals angle out from normal", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ReflectionRefraction_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectionRefraction_p2.mp3", time_offset=0)
        title = Text("Reflection and Snell Law  (Bennett 3.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'n_i\sin\theta_i=n_t\sin\theta_t', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Snell Law  (Bennett Eq. 3.2)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ReflectionRefraction_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectionRefraction_p3.mp3", time_offset=0)
        title = Text("Reflection and Snell Law  (Bennett 3.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("n increases: beam bends toward normal | n decreases: bends away", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class ReflectionRefraction_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectionRefraction_p4.mp3", time_offset=0)
        title = Text("Reflection and Snell Law  (Bennett 3.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Frequency is conserved at any interface — only wavelength changes", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class ReflectionRefraction_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectionRefraction_p5.mp3", time_offset=0)
        title = Text("Reflection and Snell Law  (Bennett 3.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'n_i=1.5,\;\theta_i=30°\;\Rightarrow\;\theta_t=48.6°', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Glass to air at 30 degrees", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ReflectionRefraction_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectionRefraction_p6.mp3", time_offset=0)
        title = Text("Reflection and Snell Law  (Bennett 3.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'n_i=1.5,\;\theta_c=41.8°\;\Rightarrow\;\sin\theta_t=1.00', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Critical angle: total internal reflection begins here", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ReflectionRefraction_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectionRefraction_p7.mp3", time_offset=0)
        title = Text("Reflection and Snell Law  (Bennett 3.2)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Above critical angle: no transmitted beam whatsoever, R equals 1 exactly", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquationsDerivation_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquationsDerivation_p1.mp3", time_offset=0)
        title = Text("Fresnel Derivation  (Bennett 3.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("From Maxwell boundary conditions: tangential E and H must be continuous", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquationsDerivation_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquationsDerivation_p2.mp3", time_offset=0)
        title = Text("Fresnel Derivation  (Bennett 3.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("S-polarisation: E field is perpendicular to the plane of incidence  (also called TE)", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquationsDerivation_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquationsDerivation_p3.mp3", time_offset=0)
        title = Text("Fresnel Derivation  (Bennett 3.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'E_i+E_r=E_t\quad n_i\cos\theta_i(E_i-E_r)=n_t\cos\theta_t E_t', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Two boundary equations for s-polarisation", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquationsDerivation_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquationsDerivation_p4.mp3", time_offset=0)
        title = Text("Fresnel Derivation  (Bennett 3.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("P-polarisation has extra cosine projection factors — gives different coefficients", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquationsDerivation_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquationsDerivation_p5.mp3", time_offset=0)
        title = Text("Fresnel Derivation  (Bennett 3.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("S and P components reflect independently — reflected beam becomes partially polarised", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquationsDerivation_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquationsDerivation_p6.mp3", time_offset=0)
        title = Text("Fresnel Derivation  (Bennett 3.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Both sets of coefficients come directly from these boundary condition equations", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p1.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Fresnel amplitude reflection and transmission coefficients", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p2.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'r_s=\frac{n_i\cos\theta_i-n_t\cos\theta_t}{n_i\cos\theta_i+n_t\cos\theta_t}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("s-polarisation reflection  (Bennett Eq. 3.11a)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p3.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r't_s=\frac{2n_i\cos\theta_i}{n_i\cos\theta_i+n_t\cos\theta_t}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("s-polarisation transmission  (Bennett Eq. 3.12a)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p4.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'r_p=\frac{n_t\cos\theta_i-n_i\cos\theta_t}{n_t\cos\theta_i+n_i\cos\theta_t}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("p-polarisation reflection  (Bennett Eq. 3.11b)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p5.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r't_p=\frac{2n_i\cos\theta_i}{n_t\cos\theta_i+n_i\cos\theta_t}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("p-polarisation transmission  (Bennett Eq. 3.12b)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p6.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'r=\frac{n_i-n_t}{n_i+n_t}\quad t=\frac{2n_i}{n_i+n_t}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Normal incidence: theta equals zero — MEMORISE these", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p7.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'r_\text{air-glass}=-0.2\quad R=0.04', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Air to glass: 4 percent reflected, pi phase shift", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p8(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p8.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Negative r means n increases at interface — causes phase shift of pi", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p9(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p9.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Positive r means n decreases at interface — no phase shift", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelEquations_p10(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelEquations_p10.mp3", time_offset=0)
        title = Text("The Fresnel Equations  (Bennett 3.4)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("These phase signs are critical for thin-film interference calculations in Week 6", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelFullExample_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelFullExample_p1.mp3", time_offset=0)
        title = Text("Worked Fresnel Example: Air to Glass 40 deg", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'n_i=1.00,\;n_t=1.50,\;\theta_i=40°', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Given: air to glass interface at 40 degrees", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelFullExample_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelFullExample_p2.mp3", time_offset=0)
        title = Text("Worked Fresnel Example: Air to Glass 40 deg", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\sin\theta_t=(1.00/1.50)\sin40°\;\Rightarrow\;\theta_t=25.4°', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 1: apply Snell law FIRST before any Fresnel calculation", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelFullExample_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelFullExample_p3.mp3", time_offset=0)
        title = Text("Worked Fresnel Example: Air to Glass 40 deg", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Compute all needed cosines: cos(40)=0.766, cos(25.4)=0.904", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class FresnelFullExample_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelFullExample_p4.mp3", time_offset=0)
        title = Text("Worked Fresnel Example: Air to Glass 40 deg", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'r_s=-0.278\;\Rightarrow\;R_s=0.0772', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 3: s-polarisation — 7.7 percent reflected", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelFullExample_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelFullExample_p5.mp3", time_offset=0)
        title = Text("Worked Fresnel Example: Air to Glass 40 deg", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'r_p=+0.119\;\Rightarrow\;R_p=0.0142', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 4: p-polarisation — 1.4 percent reflected, near Brewster angle", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FresnelFullExample_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FresnelFullExample_p6.mp3", time_offset=0)
        title = Text("Worked Fresnel Example: Air to Glass 40 deg", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'R_s+T_s=1.000\;\checkmark\quad R_p+T_p=1.000\;\checkmark', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 5: verify energy conservation — must always do this", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ReflectivityTransmissivity_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectivityTransmissivity_p1.mp3", time_offset=0)
        title = Text("Reflectivity and Transmissivity", font_size=28, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'R=|r|^2', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Reflectivity = modulus squared of amplitude reflection coefficient", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ReflectivityTransmissivity_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectivityTransmissivity_p2.mp3", time_offset=0)
        title = Text("Reflectivity and Transmissivity", font_size=28, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'T=\frac{n_t\cos\theta_t}{n_i\cos\theta_i}|t|^2', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Transmissivity — NOT simply t-squared, beam cross-section changes", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ReflectivityTransmissivity_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectivityTransmissivity_p3.mp3", time_offset=0)
        title = Text("Reflectivity and Transmissivity", font_size=28, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'R+T=1', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Energy conservation — ALWAYS verify this at the end", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ReflectivityTransmissivity_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectivityTransmissivity_p4.mp3", time_offset=0)
        title = Text("Reflectivity and Transmissivity", font_size=28, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Writing T equals t-squared is the single most common fatal error here", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class ReflectivityTransmissivity_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ReflectivityTransmissivity_p5.mp3", time_offset=0)
        title = Text("Reflectivity and Transmissivity", font_size=28, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("10-surface camera lens with no AR coating: only 67 percent transmitted", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class BrewsterTIR_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/BrewsterTIR_p1.mp3", time_offset=0)
        title = Text("Brewster Angle and Total Internal Reflection  (Bennett 3.5)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\tan\theta_B=n_t/n_i', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Brewster angle — r_p equals zero exactly, no p-reflection", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class BrewsterTIR_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/BrewsterTIR_p2.mp3", time_offset=0)
        title = Text("Brewster Angle and Total Internal Reflection  (Bennett 3.5)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\theta_B=\arctan(1.5)=56.3°', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Brewster angle for n equals 1.5 glass", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class BrewsterTIR_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/BrewsterTIR_p3.mp3", time_offset=0)
        title = Text("Brewster Angle and Total Internal Reflection  (Bennett 3.5)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\sin\theta_c=n_t/n_i\quad(n_i>n_t)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Critical angle for total internal reflection", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class BrewsterTIR_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/BrewsterTIR_p4.mp3", time_offset=0)
        title = Text("Brewster Angle and Total Internal Reflection  (Bennett 3.5)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\theta_c=\arcsin(1/1.5)=41.8°', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Critical angle from n=1.5 glass to air", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class BrewsterTIR_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/BrewsterTIR_p5.mp3", time_offset=0)
        title = Text("Brewster Angle and Total Internal Reflection  (Bennett 3.5)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("At Brewster angle: reflected and refracted beams are exactly perpendicular", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class BrewsterTIR_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/BrewsterTIR_p6.mp3", time_offset=0)
        title = Text("Brewster Angle and Total Internal Reflection  (Bennett 3.5)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Laser Brewster windows: p-polarisation passes with absolutely zero reflection loss", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class BrewsterTIR_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/BrewsterTIR_p7.mp3", time_offset=0)
        title = Text("Brewster Angle and Total Internal Reflection  (Bennett 3.5)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("TIR gives R equals 1.000 exactly — used in optical fibres and dove prisms", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class BrewsterTIR_p8(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/BrewsterTIR_p8.mp3", time_offset=0)
        title = Text("Brewster Angle and Total Internal Reflection  (Bennett 3.5)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Diamond: critical angle only 24.4 degrees — total reflection makes it sparkle", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class MalusLaw_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MalusLaw_p1.mp3", time_offset=0)
        title = Text("Malus Law  (Bennett 6.2.1)", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I=I_0\cos^2\theta', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Malus Law  (Bennett Eq. 6.6)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MalusLaw_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MalusLaw_p2.mp3", time_offset=0)
        title = Text("Malus Law  (Bennett 6.2.1)", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("theta=0: full transmission | theta=90 degrees: complete extinction", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class MalusLaw_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MalusLaw_p3.mp3", time_offset=0)
        title = Text("Malus Law  (Bennett 6.2.1)", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Three polarisers: horizontal at 0, at 45 degrees, vertical at 90", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class MalusLaw_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MalusLaw_p4.mp3", time_offset=0)
        title = Text("Malus Law  (Bennett 6.2.1)", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I_0\xrightarrow{H}I_0/2\xrightarrow{45°}I_0/4\xrightarrow{V}I_0/8', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Chain result: I0 divided by 8 — middle polariser is essential", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MalusLaw_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MalusLaw_p5.mp3", time_offset=0)
        title = Text("Malus Law  (Bennett 6.2.1)", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Without middle polariser: output is exactly zero", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class MalusLaw_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MalusLaw_p6.mp3", time_offset=0)
        title = Text("Malus Law  (Bennett 6.2.1)", font_size=38, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Unpolarised light through one polariser: I0 divided by 2, average of cos-squared", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)
