# week6_interference.py — generated by gen_final.py
from manim import *
from utils import *

class Week6TitleCard_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week6TitleCard_p1.mp3", time_offset=0)
        card = make_title_card("WEEK 6", "Interference and Coherence", "Bennett Ch. 7")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Week 6: interference — the wave nature of light made directly visible", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week6TitleCard_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week6TitleCard_p2.mp3", time_offset=0)
        card = make_title_card("WEEK 6", "Interference and Coherence", "Bennett Ch. 7")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Two coherent beams: intensity from 0 to 4*I0", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week6TitleCard_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week6TitleCard_p3.mp3", time_offset=0)
        card = make_title_card("WEEK 6", "Interference and Coherence", "Bennett Ch. 7")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Key topics: two-beam formula, Young, thin film, coherence", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week6TitleCard_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week6TitleCard_p4.mp3", time_offset=0)
        card = make_title_card("WEEK 6", "Interference and Coherence", "Bennett Ch. 7")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Applications: AR coatings, LIGO, holography", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class InterferenceIntroScene_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/InterferenceIntroScene_p1.mp3", time_offset=0)
        title = Text("Introduction to Interference  (Bennett 7.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I=I_1+I_2+2\sqrt{I_1 I_2}\cos\delta', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Two-beam interference formula  (Bennett Eq. 7.14)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class InterferenceIntroScene_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/InterferenceIntroScene_p2.mp3", time_offset=0)
        title = Text("Introduction to Interference  (Bennett 7.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta=0\;\Rightarrow\;I_\text{max}=(\sqrt{I_1}+\sqrt{I_2})^2=4I_0', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Constructive: crests aligned, maximum intensity", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class InterferenceIntroScene_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/InterferenceIntroScene_p3.mp3", time_offset=0)
        title = Text("Introduction to Interference  (Bennett 7.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta=\pi\;\Rightarrow\;I_\text{min}=(\sqrt{I_1}-\sqrt{I_2})^2=0\;\text{(equal beams)}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Destructive: crest meets trough, zero intensity", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class InterferenceIntroScene_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/InterferenceIntroScene_p4.mp3", time_offset=0)
        title = Text("Introduction to Interference  (Bennett 7.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Equal beams I1=I2=I0: intensity ranges from zero to four times I0", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class InterferenceIntroScene_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/InterferenceIntroScene_p5.mp3", time_offset=0)
        title = Text("Introduction to Interference  (Bennett 7.3)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'l_c=\frac{\lambda^2}{\Delta\lambda}=\frac{c}{\Delta\nu}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Coherence length: OPD must be less than l_c for fringes", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class TwoBeamInterference_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/TwoBeamInterference_p1.mp3", time_offset=0)
        title = Text("Two-Beam Interference  (Bennett 7.3.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I=I_1+I_2+2\sqrt{I_1 I_2}\cos\delta\quad\delta=\phi_2-\phi_1', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Interference formula — cross term arises from modulus squared", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class TwoBeamInterference_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/TwoBeamInterference_p2.mp3", time_offset=0)
        title = Text("Two-Beam Interference  (Bennett 7.3.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta=\frac{2\pi}{\lambda}\cdot\text{OPD}+\Delta\phi_\text{refl}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Total phase difference: geometric path difference plus reflection phase shifts", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class TwoBeamInterference_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/TwoBeamInterference_p3.mp3", time_offset=0)
        title = Text("Two-Beam Interference  (Bennett 7.3.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'2\sqrt{I_1 I_2}\cos\delta\;\text{: interference term — can be + or -}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Cross term: positive = constructive, negative = destructive", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class TwoBeamInterference_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/TwoBeamInterference_p4.mp3", time_offset=0)
        title = Text("Two-Beam Interference  (Bennett 7.3.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Track both reflection phase shifts — missing one gives wrong interference condition", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class TwoBeamInterference_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/TwoBeamInterference_p5.mp3", time_offset=0)
        title = Text("Two-Beam Interference  (Bennett 7.3.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta y=\frac{\lambda L}{d}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Fringe spacing — derived from path difference = m*lambda", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class YoungDoubleSlit_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/YoungDoubleSlit_p1.mp3", time_offset=0)
        title = Text("Young Double-Slit  (Bennett 7.3.2.1)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'd\sin\theta_m=m\lambda', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Bright fringe condition  (Bennett Eq. 7.18)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class YoungDoubleSlit_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/YoungDoubleSlit_p2.mp3", time_offset=0)
        title = Text("Young Double-Slit  (Bennett 7.3.2.1)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta y=\frac{\lambda L}{d}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Fringe spacing  (Bennett Eq. 7.19) — KEY formula to memorise", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class YoungDoubleSlit_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/YoungDoubleSlit_p3.mp3", time_offset=0)
        title = Text("Young Double-Slit  (Bennett 7.3.2.1)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I=4I_0\cos^2\!\left(\frac{\pi dy}{\lambda L}\right)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Full intensity pattern as function of screen position y", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class YoungDoubleSlit_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/YoungDoubleSlit_p4.mp3", time_offset=0)
        title = Text("Young's Double-Slit  (Bennett 7.3.2.1)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'd\sin\theta_m=(m+\tfrac{1}{2})\lambda\;\Rightarrow\;\text{dark fringes}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Destructive: path difference = half-integer wavelengths", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class YoungDoubleSlit_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/YoungDoubleSlit_p5.mp3", time_offset=0)
        title = Text("Young Double-Slit  (Bennett 7.3.2.1)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'y_5=5\times\Delta y=44.2\,\text{mm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Fifth bright fringe above centre at 44.2 mm", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class YoungDoubleSlit_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/YoungDoubleSlit_p6.mp3", time_offset=0)
        title = Text("Young's Double-Slit  (Bennett 7.3.2.1)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'd=0.1\,\text{mm},\;L=1.5\,\text{m},\;\lambda=589\,\text{nm}\;\Rightarrow\;\Delta y=8.84\,\text{mm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Numerical example: fringe spacing 8.84 mm", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class YoungDoubleSlit_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/YoungDoubleSlit_p7.mp3", time_offset=0)
        title = Text("Young's Double-Slit  (Bennett 7.3.2.1)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I=4I_0\cos^2\!\left(\frac{\pi dy}{\lambda L}\right)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Full intensity pattern — cosine squared", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p1.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta=\frac{4\pi n_f t\cos\theta_t}{\lambda_0}+\Delta\phi_\text{refl}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Total phase for thin film  (Bennett Eq. 7.26)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p2.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta=\frac{4\pi n_f t\cos\theta_t}{\lambda_0}+\Delta\phi_\text{refl}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Total phase: geometric OPD + reflection phase shifts", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p3.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\phi_\text{refl}=\begin{cases}\pi&n\text{ increases}\\0&n\text{ decreases}\end{cases}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Reflection phase shift rule — critical for thin films", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p4.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'2n_f t=\lambda/2\;\Rightarrow\;t=\lambda_0/(4n_f)=99.6\,\text{nm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("AR coating: MgF2 on glass — both reflections get plus-pi, net zero", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p5.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{List reflections}\;\to\;\Delta\phi_\text{each}\;\to\;\Delta\phi_\text{net}=\Delta\phi_2-\Delta\phi_1', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Systematic approach: track each reflection separately", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p6.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'n_\text{air}=1<n_\text{MgF}_2=1.38<n_\text{glass}=1.52', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("AR coating: MgF2 on glass — both reflections get +pi phase", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p7.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Both surfaces must be tracked separately — tracking only one is wrong", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p8(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p8.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Normal incidence: cos theta_t equals 1, simplifies the geometric phase term", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p9(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p9.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\phi_\text{net}=\pi-\pi=0\;\Rightarrow\;\text{destructive when }2n_f t=\lambda/2', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Net zero phase shift: destructive when 2nft = lambda/2", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class ThinFilmInterference_p10(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/ThinFilmInterference_p10.mp3", time_offset=0)
        title = Text("Thin Film Interference  (Bennett 7.3.3)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r't=\frac{\lambda_0}{4n_f}=\frac{550}{4\times1.38}=99.6\,\text{nm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("AR coating thickness for 550 nm design wavelength", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FringeVisibility_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FringeVisibility_p1.mp3", time_offset=0)
        title = Text("Fringe Visibility and Coherence  (Bennett 7.3.4)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'V=\frac{I_\text{max}-I_\text{min}}{I_\text{max}+I_\text{min}}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Fringe visibility  (Bennett Eq. 7.30)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FringeVisibility_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FringeVisibility_p2.mp3", time_offset=0)
        title = Text("Fringe Visibility and Coherence  (Bennett 7.3.4)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'V=\frac{2\sqrt{I_1 I_2}}{I_1+I_2}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Visibility maximised when I1 equals I2 — balanced beams", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FringeVisibility_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FringeVisibility_p3.mp3", time_offset=0)
        title = Text("Fringe Visibility and Coherence  (Bennett 7.3.4)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'l_c=\lambda^2/\Delta\lambda=c/\Delta\nu', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Coherence length — OPD must be less than this for fringes to appear", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FringeVisibility_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FringeVisibility_p4.mp3", time_offset=0)
        title = Text("Fringe Visibility and Coherence  (Bennett 7.3.4)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'l_c=\frac{\lambda^2}{\Delta\lambda}=\frac{c}{\Delta\nu}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Coherence length — OPD must be less than l_c", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FringeVisibility_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FringeVisibility_p5.mp3", time_offset=0)
        title = Text("Fringe Visibility and Coherence  (Bennett 7.3.4)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Stellar interferometry: visibility versus baseline gives stellar angular diameter", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class MichelsonScene_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MichelsonScene_p1.mp3", time_offset=0)
        title = Text("Michelson Interferometer  (Bennett 7.8)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'N=2\Delta L/\lambda', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Fringe count N when mirror moves distance delta-L", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MichelsonScene_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MichelsonScene_p2.mp3", time_offset=0)
        title = Text("Michelson Interferometer  (Bennett 7.8)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{RP}=2L/\lambda', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Resolving power equals 2L over lambda", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MichelsonScene_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MichelsonScene_p3.mp3", time_offset=0)
        title = Text("Michelson Interferometer  (Bennett 7.8)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'N=\frac{2\Delta L}{\lambda}\;\Rightarrow\;\Delta L=\frac{N\lambda}{2}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Mirror displacement from fringe count", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MichelsonScene_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MichelsonScene_p4.mp3", time_offset=0)
        title = Text("Michelson Interferometer  (Bennett 7.8)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("LIGO: 4 km arms with Fabry-Perot cavities giving 1600 km effective path length", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class MichelsonScene_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MichelsonScene_p5.mp3", time_offset=0)
        title = Text("Michelson Interferometer  (Bennett 7.8)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta L_\text{LIGO}=10^{-18}\,\text{m}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("LIGO strain sensitivity: one ten-thousandth of a proton diameter, 2015 detection", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)
