# week8_fabry_perot.py — generated by gen_final.py
from manim import *
from utils import *

class Week8TitleCard_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8TitleCard_p1.mp3", time_offset=0)
        card = make_title_card("WEEK 8", "Fabry-Perot Interferometer", "Bennett 7.10-7.12")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Week 8: Fabry-Perot interferometer  (Bennett 7.10 through 7.12)", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week8TitleCard_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8TitleCard_p2.mp3", time_offset=0)
        card = make_title_card("WEEK 8", "Fabry-Perot Interferometer", "Bennett 7.10-7.12")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Multiple reflections produce geometric series — sums to the Airy function", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week8TitleCard_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8TitleCard_p3.mp3", time_offset=0)
        card = make_title_card("WEEK 8", "Fabry-Perot Interferometer", "Bennett 7.10-7.12")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Sharp resonance peaks: 100% transmission at resonance", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week8TitleCard_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8TitleCard_p4.mp3", time_offset=0)
        card = make_title_card("WEEK 8", "Fabry-Perot Interferometer", "Bennett 7.10-7.12")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Resolving power far exceeds diffraction gratings", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class MultiBeamIntro_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MultiBeamIntro_p1.mp3", time_offset=0)
        title = Text("Multi-Beam Interference  (Bennett 7.10)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I_t^\text{Michelson}\propto1+\cos\delta,\quad I_t^\text{FP}=\frac{I_0}{1+F\sin^2(\delta/2)}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Michelson: 2 beams, sinusoidal. FP: multiple beams, sharp peaks", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MultiBeamIntro_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MultiBeamIntro_p2.mp3", time_offset=0)
        title = Text("Multi-Beam Interference  (Bennett 7.10)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\tilde{T}=\frac{t^2}{1-r^2 e^{i\delta}}\quad\delta=\frac{4\pi nd\cos\theta}{\lambda}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Geometric series summed exactly  (Bennett 7.10)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MultiBeamIntro_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MultiBeamIntro_p3.mp3", time_offset=0)
        title = Text("Multi-Beam Interference  (Bennett 7.10)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\tilde{E}_t=\frac{t^2}{1-r^2 e^{i\delta}}\tilde{E}_i,\quad\delta=\frac{4\pi nd\cos\theta}{\lambda}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Geometric series gives exact transmitted amplitude", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class MultiBeamIntro_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/MultiBeamIntro_p4.mp3", time_offset=0)
        title = Text("Multi-Beam Interference  (Bennett 7.10)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta=2N\pi\;\Rightarrow\;I_t=I_0\;\text{regardless of }R', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("At resonance: 100% transmission for any R", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class AiryFunction_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/AiryFunction_p1.mp3", time_offset=0)
        title = Text("The Airy Function  (Bennett Eq. 7.89)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I_t=\frac{I_0}{1+F\sin^2(\delta/2)}\quad F=\frac{4R}{(1-R)^2}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("The Airy function  (Bennett Eq. 7.89)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class AiryFunction_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/AiryFunction_p2.mp3", time_offset=0)
        title = Text("The Airy Function  (Bennett Eq. 7.89)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta=2N\pi\;\Rightarrow\;\sin(\delta/2)=0\;\Rightarrow\;I_t=I_0', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("At resonance: sine term vanishes, full transmission", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class AiryFunction_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/AiryFunction_p3.mp3", time_offset=0)
        title = Text("The Airy Function  (Bennett Eq. 7.89)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta=2N\pi\;\Rightarrow\;I_t=I_0', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("At resonance: 100 percent transmission regardless of reflectivity R", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class AiryFunction_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/AiryFunction_p4.mp3", time_offset=0)
        title = Text("The Airy Function  (Bennett Eq. 7.89)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'R=0.9:\;F=360\;\Rightarrow\;I_t^\text{off-res}<0.3\%', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Off resonance at R=0.9: less than 0.3 percent transmits", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class AiryFunction_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/AiryFunction_p5.mp3", time_offset=0)
        title = Text("The Airy Function  (Bennett Eq. 7.89)", font_size=34, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'F=\frac{4R}{(1-R)^2}\;\nearrow\;\text{as }R\to1\;\Rightarrow\;\text{sharper peaks}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Higher R: larger F, sharper peaks, better resolving power", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FinesseResolving_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FinesseResolving_p1.mp3", time_offset=0)
        title = Text("Finesse, Resolving Power and Free Spectral Range", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\mathcal{F}=\frac{\pi\sqrt{R}}{1-R}=\frac{\pi\sqrt{F}}{2}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("FINESSE script-F  (NOT the same as capital F)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FinesseResolving_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FinesseResolving_p2.mp3", time_offset=0)
        title = Text("Finesse, Resolving Power and Free Spectral Range", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'N=2nd\cos\theta/\lambda_0', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Order number at resonance", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FinesseResolving_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FinesseResolving_p3.mp3", time_offset=0)
        title = Text("Finesse, Resolving Power and Free Spectral Range", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{RP}=N\mathcal{F}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Resolving power equals order number times FINESSE", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FinesseResolving_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FinesseResolving_p4.mp3", time_offset=0)
        title = Text("Finesse, Resolving Power and Free Spectral Range", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\lambda_\text{FSR}=\lambda_0^2/(2nd)\quad\Delta\nu_\text{FSR}=c/(2nd)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Free spectral range in wavelength and in frequency", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FinesseResolving_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FinesseResolving_p5.mp3", time_offset=0)
        title = Text("Finesse, Resolving Power and Free Spectral Range", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'R=0.9:\;\mathcal{F}=29.8\qquad R=0.99:\;\mathcal{F}=312', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Finesse values for R=0.9 and R=0.99", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FinesseResolving_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FinesseResolving_p6.mp3", time_offset=0)
        title = Text("Finesse, Resolving Power and FSR", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'F=\frac{4\times0.9}{(0.1)^2}=360,\quad\mathcal{F}=\frac{\pi\sqrt{0.9}}{0.1}=29.8', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("R=0.9: F=360 but script-F=29.8 — very different numbers", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FabryPerotExample_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FabryPerotExample_p1.mp3", time_offset=0)
        title = Text("Worked Fabry-Perot Example: H and D Alpha Lines", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'R=0.90,\;\lambda_0=656.2\,\text{nm},\;\Delta\lambda=0.18\,\text{nm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Resolving H-alpha from D-alpha lines  (Bennett Example 7.11)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FabryPerotExample_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FabryPerotExample_p2.mp3", time_offset=0)
        title = Text("Worked Fabry-Perot Example: H and D Alpha Lines", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'F=360\;\Rightarrow\;\mathcal{F}=29.8', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 1: compute coefficient F and finesse script-F", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FabryPerotExample_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FabryPerotExample_p3.mp3", time_offset=0)
        title = Text("Worked Fabry-Perot Example: H and D Alpha Lines", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'd=\lambda_0^2/(2\Delta\lambda_\text{FSR})=0.431\,\text{mm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 2: choose FSR=0.5nm, find required mirror spacing", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FabryPerotExample_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FabryPerotExample_p4.mp3", time_offset=0)
        title = Text("Worked Fabry-Perot Example: H and D Alpha Lines", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'N=2d/\lambda_0=1313', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 3: order number from spacing and wavelength", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FabryPerotExample_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FabryPerotExample_p5.mp3", time_offset=0)
        title = Text("Worked Fabry-Perot Example: H and D Alpha Lines", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{RP}=1313\times29.8=39100', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 4: resolving power = order times finesse", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FabryPerotExample_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FabryPerotExample_p6.mp3", time_offset=0)
        title = Text("Worked Fabry-Perot Example: H and D Alpha Lines", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta\lambda_\text{min}=656.2/39100=0.017\,\text{nm}\ll0.18\,\text{nm}\;\checkmark', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 5: verify — minimum resolvable much less than target separation", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FabryPerotExample_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FabryPerotExample_p7.mp3", time_offset=0)
        title = Text("Worked Fabry-Perot Example", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta\lambda_\text{min}=\frac{\lambda_0}{\text{RP}}=\frac{656.2}{39100}=0.017\,\text{nm}\ll0.18\,\text{nm}\;\checkmark', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Step 5: verify — minimum resolvable much smaller than target", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class FabryPerotExample_p8(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/FabryPerotExample_p8.mp3", time_offset=0)
        title = Text("Worked Fabry-Perot Example", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{RP}_\text{FP}=39100\gg\text{RP}_\text{grating}=30000', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("FP beats best grating at same aperture", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CoherenceLength_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CoherenceLength_p1.mp3", time_offset=0)
        title = Text("Coherence Length and Fabry-Perot  (Bennett 7.12)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'l_c=\lambda^2/\Delta\lambda=c/\Delta\nu', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Coherence length  (Bennett 7.12)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CoherenceLength_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CoherenceLength_p2.mp3", time_offset=0)
        title = Text("Coherence Length and Fabry-Perot  (Bennett 7.12)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'l_c=\frac{\lambda^2}{\Delta\lambda}=\frac{c}{\Delta\nu}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Coherence length formula  (Bennett 7.12)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CoherenceLength_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CoherenceLength_p3.mp3", time_offset=0)
        title = Text("Coherence Length and Fabry-Perot  (Bennett 7.12)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\tau_c=\frac{l_c}{c}=\frac{1}{\Delta\nu}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Coherence time = inverse of linewidth", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CoherenceLength_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CoherenceLength_p4.mp3", time_offset=0)
        title = Text("Coherence Length and Fabry-Perot  (Bennett 7.12)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("White light: Delta-lambda ~300 nm -> l_c ~ 1 micron — only 2-3 fringes", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class CoherenceLength_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CoherenceLength_p5.mp3", time_offset=0)
        title = Text("Coherence Length and Fabry-Perot  (Bennett 7.12)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\lambda\approx0.6\,\text{nm}\;\Rightarrow\;l_c=\frac{589^2}{0.6}\approx0.58\,\text{mm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Na D lines: coherence length ~0.58 mm", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CoherenceLength_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CoherenceLength_p6.mp3", time_offset=0)
        title = Text("Coherence Length and Fabry-Perot  (Bennett 7.12)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\nu\approx1\,\text{MHz}\;\Rightarrow\;l_c=\frac{c}{\Delta\nu}=300\,\text{m}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("He-Ne laser: coherence length ~300 m", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CoherenceLength_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CoherenceLength_p7.mp3", time_offset=0)
        title = Text("Coherence Length and Fabry-Perot  (Bennett 7.12)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\nu\sim\text{mHz}\;\Rightarrow\;l_c\sim\frac{3\times10^8}{10^{-3}}=3\times10^{11}\,\text{m}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("LIGO laser: coherence length > Earth-Sun distance", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class Week8Summary_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8Summary_p1.mp3", time_offset=0)
        title = Text("Week 8 Summary: All Fabry-Perot Formulas", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I_t=\frac{I_0}{1+F\sin^2(\delta/2)},\quad F=\frac{4R}{(1-R)^2},\quad\delta=\frac{4\pi nd}{\lambda_0}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("All Fabry-Perot formulas  (Bennett 7.10-7.12)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class Week8Summary_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8Summary_p2.mp3", time_offset=0)
        title = Text("Week 8 Summary: All Fabry-Perot Formulas", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I_t=\frac{I_0}{1+F\sin^2(\delta/2)}\quad F=\frac{4R}{(1-R)^2}\quad\delta=\frac{4\pi nd}{\lambda_0}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Airy function, coefficient of finesse F, and round-trip phase", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class Week8Summary_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8Summary_p3.mp3", time_offset=0)
        title = Text("Week 8 Summary: All Fabry-Perot Formulas", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\mathcal{F}=\frac{\pi\sqrt{R}}{1-R}\quad N=\frac{2nd}{\lambda_0}\quad\text{RP}=N\mathcal{F}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Finesse script-F, order number N, and resolving power", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class Week8Summary_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8Summary_p4.mp3", time_offset=0)
        title = Text("Week 8 Summary: All Fabry-Perot Formulas", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\lambda_\text{FSR}=\lambda_0^2/(2nd)\quad\Delta\nu_\text{FSR}=c/(2nd)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Free spectral range in both wavelength and frequency", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class Week8Summary_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8Summary_p5.mp3", time_offset=0)
        title = Text("Week 8 Summary: All Fabry-Perot Formulas", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'N=\frac{2nd\cos\theta}{\lambda_0}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Order number at resonance", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class Week8Summary_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8Summary_p6.mp3", time_offset=0)
        title = Text("Week 8 Summary: All Fabry-Perot Formulas", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{RP}=N\mathcal{F}=\frac{2nd}{\lambda_0}\cdot\frac{\pi\sqrt{R}}{1-R}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Resolving power = order times finesse", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class Week8Summary_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8Summary_p7.mp3", time_offset=0)
        title = Text("Week 8 Summary: All Fabry-Perot Formulas", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\lambda_\text{FSR}=\frac{\lambda_0^2}{2nd},\quad\Delta\nu_\text{FSR}=\frac{c}{2nd}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Free spectral range in wavelength and frequency", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class Week8Summary_p8(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week8Summary_p8.mp3", time_offset=0)
        title = Text("Week 8 Summary: All Fabry-Perot Formulas", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'2nd<l_c=\frac{\lambda^2}{\Delta\lambda}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Coherence requirement for Fabry-Perot operation", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)
