# week7_diffraction.py — generated by gen_final.py
from manim import *
from utils import *

class Week7TitleCard_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week7TitleCard_p1.mp3", time_offset=0)
        card = make_title_card("WEEK 7", "Fraunhofer Diffraction", "Bennett Ch. 8")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Week 7: diffraction — wave optics when aperture is comparable to wavelength", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week7TitleCard_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week7TitleCard_p2.mp3", time_offset=0)
        card = make_title_card("WEEK 7", "Fraunhofer Diffraction", "Bennett Ch. 8")
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Fraunhofer pattern = Fourier transform of aperture", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class Week7TitleCard_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week7TitleCard_p3.mp3", time_offset=0)
        card = make_title_card("WEEK 7", "Fraunhofer Diffraction", "Bennett Ch. 8")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Larger aperture gives narrower diffraction pattern — optical uncertainty principle", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class Week7TitleCard_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/Week7TitleCard_p4.mp3", time_offset=0)
        card = make_title_card("WEEK 7", "Fraunhofer Diffraction", "Bennett Ch. 8")
        rule = bottom_rule()
        self.play(FadeIn(card, run_time=0.5))
        sub_t = Text("Bennett Chapter 8: diffraction treated as interference from an extended source", font_size=24, color=BLUE_LIGHT)
        safe_scale(sub_t, max_width=12.0)
        sub_t.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(sub_t, shift=UP*0.15, run_time=0.4))
        self.add(rule)
        self.wait(120)

class HuygensPrinciple_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/HuygensPrinciple_p1.mp3", time_offset=0)
        title = Text("Huygens' Principle  (Bennett 8.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Huygens 1678: every wavefront point is a secondary spherical source  (Bennett 8.2)", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class HuygensPrinciple_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/HuygensPrinciple_p2.mp3", time_offset=0)
        title = Text("Huygens Principle  (Bennett 8.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'L\gg a^2/(2\lambda)', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Fraunhofer condition: far-field observation, or equivalently, a lens in the aperture", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class HuygensPrinciple_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/HuygensPrinciple_p3.mp3", time_offset=0)
        title = Text("Huygens' Principle  (Bennett 8.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'L\gg\frac{a^2}{2\lambda}\;\Rightarrow\;\text{Fraunhofer regime}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Fraunhofer condition: far-field or equivalently a lens in aperture", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class HuygensPrinciple_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/HuygensPrinciple_p4.mp3", time_offset=0)
        title = Text("Huygens' Principle  (Bennett 8.2)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'U(\theta)\propto\int_\text{aperture}e^{ikx\sin\theta}\,dx=\mathcal{F}\{A(x)\}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Far field = Fourier transform of aperture function", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SingleSlitDiffraction_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SingleSlitDiffraction_p1.mp3", time_offset=0)
        title = Text("Single-Slit Diffraction  (Bennett 8.3.1)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'I=I_0\!\left(\frac{\sin\beta}{\beta}\right)^2\quad\beta=\frac{\pi b\sin\theta}{\lambda}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Single-slit sinc-squared pattern  (Bennett 8.3.1)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SingleSlitDiffraction_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SingleSlitDiffraction_p2.mp3", time_offset=0)
        title = Text("Single-Slit Diffraction  (Bennett 8.3.1)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'b\sin\theta=m\lambda', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Dark minima condition — zeros of the sinc-squared function", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SingleSlitDiffraction_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SingleSlitDiffraction_p3.mp3", time_offset=0)
        title = Text("Single-Slit Diffraction  (Bennett 8.3.1)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\theta_\text{half}=\lambda/b\;\text{[rad]}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Half-width of central maximum in radians", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SingleSlitDiffraction_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SingleSlitDiffraction_p4.mp3", time_offset=0)
        title = Text("Single-Slit Diffraction  (Bennett 8.3.1)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Narrower slit gives wider central maximum — inverse relationship", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class SingleSlitDiffraction_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SingleSlitDiffraction_p5.mp3", time_offset=0)
        title = Text("Single-Slit Diffraction  (Bennett 8.3.1)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Secondary maxima have 4.7 percent and 1.7 percent of central peak intensity", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class SingleSlitDiffraction_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SingleSlitDiffraction_p6.mp3", time_offset=0)
        title = Text("Single-Slit Diffraction  (Bennett 8.3.1)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'b=0.2\,\text{mm},\;\lambda=633\,\text{nm},\;L=2\,\text{m}:\;y_1=6.33\,\text{mm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Worked example: first minimum at 6.33 mm", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class SingleSlitDiffraction_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/SingleSlitDiffraction_p7.mp3", time_offset=0)
        title = Text("Single-Slit Diffraction  (Bennett 8.3.1)", font_size=32, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'b=0.200\,\text{mm},\;\lambda=633\,\text{nm},\;L=2\,\text{m}\;\Rightarrow\;y_1=\frac{\lambda L}{b}=6.33\,\text{mm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Complete numerical example: first minimum at 6.33 mm", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CircularApertureRayleigh_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CircularApertureRayleigh_p1.mp3", time_offset=0)
        title = Text("Circular Aperture and Rayleigh Criterion  (Bennett 8.3.3)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\sin\theta_1=1.22\lambda/D', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("First dark ring — factor 1.22 from first zero of Bessel function J1  (Bennett 8.3.3)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CircularApertureRayleigh_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CircularApertureRayleigh_p2.mp3", time_offset=0)
        title = Text("Circular Aperture and Rayleigh Criterion  (Bennett 8.3.3)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\theta_\text{min}=1.22\lambda/D', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Rayleigh criterion: minimum resolvable angular separation", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CircularApertureRayleigh_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CircularApertureRayleigh_p3.mp3", time_offset=0)
        title = Text("Circular Aperture and Rayleigh Criterion  (Bennett 8.3.3)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\theta_\text{eye}=1.22\times550\,\text{nm}/3\,\text{mm}=46\,\text{arcsec}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Human eye resolution limit", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CircularApertureRayleigh_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CircularApertureRayleigh_p4.mp3", time_offset=0)
        title = Text("Circular Aperture and Rayleigh Criterion  (Bennett 8.3.3)", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\theta_\text{HST}=1.22\times550\,\text{nm}/2.4\,\text{m}=0.058\,\text{arcsec}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Hubble Space Telescope: 800 times sharper than naked eye", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CircularApertureRayleigh_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CircularApertureRayleigh_p5.mp3", time_offset=0)
        title = Text("Circular Aperture and Rayleigh Criterion", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'D_\text{eye}\approx3\,\text{mm}\;\Rightarrow\;\theta_\text{min}=\frac{1.22\times550\,\text{nm}}{3\,\text{mm}}=2.2\times10^{-4}\,\text{rad}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Human eye resolution limit", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CircularApertureRayleigh_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CircularApertureRayleigh_p6.mp3", time_offset=0)
        title = Text("Circular Aperture and Rayleigh Criterion", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'D_\text{HST}=2.4\,\text{m}\;\Rightarrow\;\theta_\text{min}=2.8\times10^{-7}\,\text{rad}=0.058\,\text{arcsec}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Hubble: 800 times sharper than naked eye", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class CircularApertureRayleigh_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/CircularApertureRayleigh_p7.mp3", time_offset=0)
        title = Text("Circular Aperture and Rayleigh Criterion", font_size=26, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        cap_t = Text("Improve resolution: increase D or decrease lambda — X-ray telescopes, VLBI radio", font_size=30, color=WHITE)
        safe_scale(cap_t, max_width=12.5)
        t_bot = rule_top.get_bottom()[1]
        cap_t.move_to([0, (t_bot + (-3.7)) / 2, 0])
        self.play(FadeIn(cap_t, shift=UP*0.15, run_time=0.4))
        self.add(bottom_rule())
        self.wait(120)

class DiffractionGrating_p1(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/DiffractionGrating_p1.mp3", time_offset=0)
        title = Text("Diffraction Grating  (Bennett 8.3.7-8.3.8)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'd\sin\theta_m=m\lambda', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Grating equation  (Bennett Eq. 8.38)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class DiffractionGrating_p2(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/DiffractionGrating_p2.mp3", time_offset=0)
        title = Text("Diffraction Grating  (Bennett 8.3.7-8.3.8)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{RP}=\lambda/\delta\lambda=Nm', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Resolving power equals N times m  (Bennett Eq. 8.42)", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class DiffractionGrating_p3(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/DiffractionGrating_p3.mp3", time_offset=0)
        title = Text("Diffraction Grating  (Bennett 8.3.7-8.3.8)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\lambda_\text{FSR}=\lambda/m', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Free spectral range in wavelength", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class DiffractionGrating_p4(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/DiffractionGrating_p4.mp3", time_offset=0)
        title = Text("Diffraction Grating  (Bennett 8.3.7-8.3.8)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\text{RP}=Nm=30000\times1=30000\;\text{for }N=30000,\;m=1', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Example: 600 gr/mm, 5 cm grating, first order", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class DiffractionGrating_p5(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/DiffractionGrating_p5.mp3", time_offset=0)
        title = Text("Diffraction Grating  (Bennett 8.3.7-8.3.8)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\delta\lambda_\text{min}=589/30000=0.020\,\text{nm}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Minimum resolvable wavelength difference", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class DiffractionGrating_p6(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/DiffractionGrating_p6.mp3", time_offset=0)
        title = Text("Diffraction Grating  (Bennett 8.3.7-8.3.8)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'\Delta\lambda_\text{FSR}=\frac{\lambda}{m}', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Free spectral range: unambiguous wavelength range", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18, stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)

class DiffractionGrating_p7(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR
        self.add_sound("narration/audio/paragraphs/DiffractionGrating_p7.mp3", time_offset=0)
        title = Text("Diffraction Grating  (Bennett 8.3.7-8.3.8)", font_size=30, color=GOLD)
        safe_scale(title, max_width=13.5)
        title.to_edge(UP, buff=0.28)
        rule_top = Line(title.get_left()+LEFT*0.1, title.get_right()+RIGHT*0.1,
                        color=GOLD, stroke_width=1.0).set_opacity(0.4)
        rule_top.next_to(title, DOWN, buff=0.08)
        self.play(Write(title, run_time=0.5), FadeIn(rule_top, run_time=0.5))
        eq = MathTex(r'd(\sin\theta_m-\sin\theta_i)=m\lambda', font_size=52)
        safe_scale(eq, max_width=12.5)
        cap_t = Text("Grating equation for oblique incidence", font_size=26, color=TEAL)
        safe_scale(cap_t, max_width=12.5)
        content = VGroup(eq, cap_t).arrange(DOWN, buff=0.35)
        t_bot = rule_top.get_bottom()[1]
        content.move_to([0, (t_bot + (-3.7)) / 2, 0])
        safe_scale(content, max_width=13.0, max_height=abs(t_bot + 3.7) - 0.3)
        box = SurroundingRectangle(eq, color=TEAL, buff=0.18,
                                   stroke_width=1.2).set_opacity(0.35)
        self.play(FadeIn(eq, shift=UP*0.2, run_time=0.45))
        self.play(FadeIn(box, run_time=0.3), FadeIn(cap_t, run_time=0.3))
        self.add(bottom_rule())
        self.wait(120)
